### ISSUE TITLE
Uncaught TypeError during page load: treeView.event is undefined

### ISSUE THREAD

**Issue by liamaharon** [ethereum/browser-solidity#1007]
### Description of issue
An error is thrown during the initial page load:
`Uncaught TypeError: Cannot read property 'register' of undefined`

![1](https://user-images.githubusercontent.com/16665596/35244445-0c3b7042-ffb8-11e7-9f8a-4353765aab85.png)

Not sure if related, but get yellow warnings in console from remix-d, which provides the treeView object:
`[remixd  ] [WARN] Any application that runs on your computer can potentially read from and write to all files in the directory.`
`[remixd  ] [WARN] Symbolinc links are not forwarded to Remix IDE`
`[remixd  ] `
`[remixd  ] [WARN] Symbolic link modification not allowed : ./contracts | /home/liam/Github/browser-solidity/contracts`

### Steps to reproduce
`git clone https://github.com/ethereum/browser-solidity && cd browser-solidity`
`npm install`
`npm start`
Navigate to 127.0.0.1:8080/

### Versions
OS: Ubuntu 16.04 LTS
Chrome version: 61.0.3163.100 (Official Build) (64-bit)
npm version: 4.2.0
node version: 7.10.1
nvm version: 0.33.0

**Comment by liamaharon** [comment]
Note that treeView is being somewhat initialised

![1](https://user-images.githubusercontent.com/16665596/35266497-616d48e8-001b-11e8-92ff-91116a357eb1.png)

Maybe related to these recent commits?
https://github.com/ethereum/remix/commit/4d23a8afe9c8365274396a4891223690a33db0f5#diff-cde72b150288c66896510ed3152f200d (see line 40)

https://github.com/ethereum/browser-solidity/commit/afee874f7142463051ac0f4f60d57050f0fc0919#diff-4b3872e86385f2fb931b0375fe866ef5 (see line 117)

**Comment by yann300** [comment]
the npm lib has been publised, should be fixed now
