### ISSUE TITLE
Add Feature: Compile Only On Demand

### ISSUE THREAD

**Issue by Denton-L** [ethereum/browser-solidity#101]
Currently, browser-solidity recompiles every time a change has been made to the file. This may be problematic, however, if the user is working with very large files as the whole browser freezes up to compile every time a change is made to a large project.

There should be an option to only compile on demand.

**Comment by redsquirrel** [comment]
We could potentially keep the auto-compile with large/many files if we decreased [the sensitivity for when to compile](https://github.com/ethereum/browser-solidity/blob/aa54d3d8b0fc9d3225f9f984b73c9d4652f38ea2/src/app/compiler.js#L30) as the files/sizes increased. And at a certain size, you'd have to use the compile button.

**Comment by chriseth** [comment]
We could also record the compilation time. If it takes x seconds to compile, we invoke the compiler only every 4x seconds. There should perhaps also be visual feedback at some point, perhaps a button with the following states:

 - no change in the source, no active compilation
 - change in the source, but waiting for timeout to trigger compilation (clicking the button at that point triggers compilation immediately)
 - compiling

**Comment by axic** [comment]
At the very least a toggle to turn on/off autocompilation (plus perhaps a "compile now" button if it is turned off) would be very useful - at least for me :)

**Comment by axic** [comment]
Well, we have both now: checkbox for auto compile and a manual trigger 😃
