### ISSUE TITLE
Getting -32603 when trying to deploy contract in live network

### ISSUE THREAD

**Issue by Betawi1** [ethereum/browser-solidity#1020]
A contract can be deployed fine in Ropsten, but when trying to deploy in live network it returned a -32603 (server error, internal xml-rpc error)

**Comment by iurimatias** [comment]
seems to be an issue in metamask, linking here for reference until we can confirm https://github.com/MetaMask/metamask-extension/issues/3117

**Comment by coopjc** [comment]
The issue is with Metamask? Huh. That's weird. It was working fine just a few days ago and they haven't seemed to say anything about it.

**Comment by iurimatias** [comment]
Closing. The issue has been reportedly fixed in infura.

**Comment by rawadrifai** [comment]
is this still going on? I'm running into the same issue, it was working fine yesterday.

**Comment by sameepsi** [comment]
Running into the same issue
