### ISSUE TITLE
Error When Creating an ERC20 Token

### ISSUE THREAD

**Issue by coopjc** [ethereum/browser-solidity#1021]
I've been going at it for hours trying to create my token, but everytime I click "create" on Remix, it says:
"Invalid JSON RPC response: {"id":11,"jsonrpc":"2.0","error":{"code":-32603}}".

I've done this before and it worked. I'm getting really annoyed! I hate using Truffle as well, so I try to use this.

I need all the help I can get. Thanks!

**Comment by yann300** [comment]
duplicate https://github.com/ethereum/browser-solidity/issues/1020

**Comment by massimo110** [comment]
Invalid JSON RPC response: {"id":36,"jsonrpc":"2.0","error":{"code":-32603}}

**Comment by massimo110** [comment]
no solution for me i try a lot time different network and pc
