### ISSUE TITLE
Etherscan verification ERROR

### ISSUE THREAD

**Issue by Cyzerx** [ethereum/browser-solidity#1047]
Contract code: https://ropsten.etherscan.io/tx/0xfa638bd829b77f4a172bc005973e78c473eb759531efb5196ec13c6876250260 
Code can be found here: https://github.com/Cyzerx/Test/blob/master/Token
Values are:
Supply - 500 tokens, Deployed contract name: XXPD DDA, Symbol: XDDA
I don't get it why I get always such error:
![12](https://user-images.githubusercontent.com/16735422/36041722-1f995906-0dd2-11e8-9447-735e3c7d8f77.PNG)

**Comment by iurimatias** [comment]
@Cyzerx are you specifying the same solc version you deployed the contract with? and with/without optimization

**Comment by Cyzerx** [comment]
Solc .16 and withouth optimization
