### ISSUE TITLE
Provide warnings when vulnerable code is detected

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/browser-solidity#106]
This project seems well positioned to help new Solidity developers avoid [known vulnerabilities](http://hackingdistributed.com/2016/06/16/scanning-live-ethereum-contracts-for-bugs/). It seems like one thing that browser-solidity could do is to detect calls to `send` and provide a warning.

Are there other vulnerabilities we could point out?

**Comment by chriseth** [comment]
Good idea!

**Comment by flyswatter** [comment]
We just wrote a bytecode analyzer for this at MetaMask earlier this week!

Feel free to use our code:
https://twitter.com/metamask_io/status/743644432000417793

**Comment by axic** [comment]
Given #107 was closed with

> Similar warnings have been added directly to the compiler, so I'm closing this PR.

Should this issue be considered closed?
