### ISSUE TITLE
"InternalCompilerError: "

### ISSUE THREAD

**Issue by EKostan** [ethereum/browser-solidity#1091]
Hello anyone can help me. I write next code and I recive result "InternalCompilerError: "
```
pragma solidity ^0.4.19;

library KeyLib 
{
    uint constant NumberCombinationsCount4 = 11;
    uint constant NumberCombinationsCount5 = 26;
    uint constant NumberCombinationsCount6 = 57;

    struct NumberIndex
    {
        bytes4 indexes;
        uint level;
    }

    
    function fillIndexMap4(NumberIndex[] indexMap) 
        public
    {
    }
}
```

**Comment by yann300** [comment]
@axic here is a more detailed output
"{"component":"general","formattedMessage":"InternalCompilerError: \n","message":"Internal compiler error (/root/project/libsolidity/codegen/CompilerUtils.cpp:726):","severity":"error","type":"InternalCompilerError"}"

**Comment by axic** [comment]
Please open these issues on https://github.com/ethereum/solidity

**Comment by yann300** [comment]
https://github.com/ethereum/solidity/issues/3563
