### ISSUE TITLE
Cannot use address as function parameter

### ISSUE THREAD

**Issue by mgdigital** [ethereum/browser-solidity#1096]
After failing to get my contract working and tearing my hair out for a while, I have created the following contract to demo what I believe to be a bug:

```
pragma solidity ^0.4.18;

contract BugDemo {

    address[] addresses;
    
    event CheckAddress(address addr);
    
    function addMe() public payable {
        if (!checkMe()) {
            addresses.push(msg.sender);
        }
    }
    
    function checkMe() public payable returns (bool) {
        return checkAddress(msg.sender);
    }
    
    function checkAddress(address _addr) public payable returns (bool) {
        CheckAddress(_addr);
        for (uint i = 0; i < addresses.length; i++) {
            if (addresses[i] == _addr) {
                return true;
            }
        }
        return false;
    }
}

```
Expected behaviour:
After deploying this contract on the Javascript VM with the default account 0xca35b7d915458ef540ade6068dfe2f44e8fa733c, first call to checkMe() should return false, after calling addMe(), checkMe() should then return true. checkAddress(0xca35b7d915458ef540ade6068dfe2f44e8fa733c) should now also return true.

Actual behaviour:
checkAddress(0xca35b7d915458ef540ade6068dfe2f44e8fa733c) always returns false.
When calling checkMe(), the following event shows in the console:
```
[
	{
		"topic": "cfd164717dc0d5fa66ba9ad6a8eca945c0dd478ed01a1c83cc54bc15c04c4c3e",
		"event": "CheckAddress",
		"args": [
			"0xca35b7d915458ef540ade6068dfe2f44e8fa733c"
		]
	}
]
```
However when calling checkAddress(0xca35b7d915458ef540ade6068dfe2f44e8fa733c), the following event shows in the console:

```
[
	{
		"topic": "cfd164717dc0d5fa66ba9ad6a8eca945c0dd478ed01a1c83cc54bc15c04c4c3e",
		"event": "CheckAddress",
		"args": [
			"0x8dfe2f44e8fa733c000000000000000000000000"
		]
	}
]
```
The address parameter has been altered from what was input.
Trying this contract on ethfiddle works as expected.
As a result of this bug `mapping(address => whatever)` does not work correctly.

**Comment by yann300** [comment]
there's a nasty bug right now, but when you call `checkAddress` have you tried to wrap the address with "" ?

**Comment by mgdigital** [comment]
Ha with the quotes it works - yes very nasty! Thanks @yann300

**Comment by mgdigital** [comment]
Closed why?
