### ISSUE TITLE
AssertionError: The field to must have byte length of 20

### ISSUE THREAD

**Issue by thebalaa** [ethereum/browser-solidity#118]
My previously working contracts no longer work in browser-solidity ( I cannot call any functions without getting the error shown below.

Even when calling 'fallback` on an empty contract. I did try with previous versions of solidity (by selecting from the dropdown) to no avail.

![screen shot 2016-07-01 at 12 59 10 pm](https://cloud.githubusercontent.com/assets/109041/16533166/ab16e99c-3f8b-11e6-9e6a-7137187af3aa.png)

```
contract Test {
}
```

**Comment by ithinuel** [comment]
Hi, 

This is due to address not being well formatted (missing '0x') when getCallButton is called.
This can be fixed by changing in file `app.js`, `line 99594` and `line 99604` from
`address: address` to `address: '0x' + address`

**Comment by Denton-L** [comment]
Thanks, I'll fix it up.
