### ISSUE TITLE
Support IPFS/Swarm for files

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#133]
Use the ipfs / swarm gateways for now.
- [ ] can we use gateway.ipfs.io for that?
- [ ] does it support CORS?

**Comment by chriseth** [comment]
They can already be loaded just fine via the gateways :-)

**Comment by axic** [comment]
Yes, but we could support Swarm through RPC also. If it makes sense.

**Comment by axic** [comment]
The *public IPFS gateway* doesn't have CORS enabled (yet): https://github.com/ipfs/go-ipfs/issues/2239
