### ISSUE TITLE
Cannot connect to my local geth node

### ISSUE THREAD

**Issue by Xophe92** [ethereum/browser-solidity#136]
Sorry to bother with an 'user issue'... 
please indicate where to post next time...

I cannot connect to my local node. I start geth this way :

geth.exe --unlock 0x2aB0Be4c3B802C4507f6cD6CcfBd16a346F6c637 --testnet --rpc --rpcaddr "localhost" --rpccorsdomain "https://ethereum.github.io" --rpcport "30303" --rpcapi "web3,db,net,eth" 

Then I set the port to 30303 in solidity browser but obtain a invalid JSON answer "".

Any help would be much appreciated.

**Comment by Denton-L** [comment]
This seems to be related to #137.

As a temporary workaround, if you are using Chrome, click the shield icon in the top-right corner and press "Load unsafe scripts".

![2016-07-25-163331_1366x731_scrot](https://cloud.githubusercontent.com/assets/9620836/17116395/9b6cac9a-5285-11e6-96e4-85a78ebcde1c.png)

**Comment by Xophe92** [comment]
i solved using --rpccorsdomain  "*" :)

geth.exe --datadir "C:\Users\Christophe\AppData\Roaming\Ethereum\privateChain"  --rpc  --rpcaddr "localhost" --rpcport "8545" --rpcapi "db,eth,net,web3" **--rpccorsdomain  "*"** --unlock 0xfa25
