### ISSUE TITLE
This page is trying to load scripts from unauthenticated sources

### ISSUE THREAD

**Issue by Denton-L** [ethereum/browser-solidity#137]
Whenever I start browser-solidity, I get a message that `This page is trying to load scripts from unauthenticated sources`. It seems to be trying to connect to my local Web3 provider even though the option for a JavaScript VM is selected by default.

On a cursory inspection, this seems to be caused by #131, @yann300.

**Comment by Denton-L** [comment]
Here is the stacktrace for when my browser encounters the error.
![2016-07-20-145519_305x334_scrot](https://cloud.githubusercontent.com/assets/9620836/16999041/07de9c4e-4e8a-11e6-8184-94536a24c1ba.png)

**Comment by axic** [comment]
@yann300 can we make something about this?

**Comment by yann300** [comment]
Yes it should be fixed by the coming remix PR

**Comment by Denton-L** [comment]
Fixed in #142.
