### ISSUE TITLE
results on JAvascript VM vs on private blockchain

### ISSUE THREAD

**Issue by Xophe92** [ethereum/browser-solidity#143]
Hi, 
I have a dummy function whoAmI in my contract

    function whoAmI() returns (address msgSender){
        msgSender = msg.sender;
    }

I have got very differnet kind of results when I use the javascript VM (in memory simulation) : 

Result: "0x000000000000000000000000ca35b7d915458ef540ade6068dfe2f44e8fa733c"
Transaction cost: 21591 gas. 
Execution cost: 319 gas.
Decoded: 
address msgSender: 0xca35b7d915458ef540ade6068dfe2f44e8fa733c

When I try over rpc on a private blockchain I get information on the trasanction but not on its results ? is it the expected behaviour, I would have love a "address msgSender: 0xca35b7d915458ef540ade6068dfe2f44e8fa733c" :

Result: {
  "blockHash": "0x80f89ad4b40e15abe62be6ee1d34e6a93c3b007a97dc96af250fef10f8abb389",
  "blockNumber": 595,
  "contractAddress": null,
  "cumulativeGasUsed": 21591,
  "from": "0xfa259e36df576bb529eaf4148382a99070881aa2",
  "gasUsed": 21591,
  "logs": [],
  "root": "6efb6955999ebe195ef648fef4001c9a28c75e78fbbf65fa0e2265367304050d",
  "to": "0xf086b4934844cc9994dbc9ba7287144575aa188f",
  "transactionHash": "0x4e044c5f85438da799a65bca220b9304b2ef9e4de1d76c90407e1695a79a19e9",
  "transactionIndex": 0
}
Transaction cost: 21591 gas.

**Comment by axic** [comment]
This is expected. There is currently no way in the RPC protocol to receive the return values of a transaction - it only works for calls (those methods with are "constant").

**Comment by Xophe92** [comment]
Damn it !
Thanks.

Regards
