### ISSUE TITLE
Move old issues / or fix them

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#15]
All issues in https://github.com/chriseth/browser-solidity/issues should be either fixed or moved here.

**Comment by Denton-L** [comment]
Would it be okay to just copy the issues and comments over, word for word?

**Comment by axic** [comment]
I think it is fine as it is, we'll slowly close off those over there. It is a good incentive to close them off earlier :smiley:

**Comment by axic** [comment]
We're closed off them (bar one pull request in progress).
