### ISSUE TITLE
Link Libraries

### ISSUE THREAD

**Issue by VoR0220** [ethereum/browser-solidity#160]
Perhaps we can link contracts by their addresses outside of the current working directory and enable ourselves to search for them by their contract address. Simply by replacing the code with the address and searching for the '0x' we then switch the context to look for addresses in the chain.

**Comment by chriseth** [comment]
Can you explain a bit more, please?

**Comment by VoR0220** [comment]
this was written some time ago, but what I think I meant to say was that we should enable importing from addresses on the chain and be able to generate bytecode inside the browser compiler by inputting what addresses are utilized...that or some complex etherscrape mechanism that we probably don't have the time to maintain :P

**Comment by redsquirrel** [comment]
I'm not 100% understanding what you're communicating @VoR0220, but I wonder if this is a place where https://github.com/ConsenSys/live-libs might be helpful?

**Comment by VoR0220** [comment]
Pretty certain this request predates livelibs...i think ill close due to lack of memory of what it was i wanted.

**Comment by redsquirrel** [comment]
Looks like this issue was created 4 days ago, right?

**Comment by axic** [comment]
@redsquirrel this is the original issue: https://github.com/chriseth/browser-solidity/issues/166
