### ISSUE TITLE
Error with storage in certain browsers / configurations

### ISSUE THREAD

**Issue by xavierlepretre** [ethereum/browser-solidity#166]
Current version at https://ethereum.github.io/browser-solidity/#version=soljson-latest.js

When loading the page, it fails to fully initialise.

<img width="359" alt="screen shot 2016-08-02 at 16 00 13" src="https://cloud.githubusercontent.com/assets/5309374/17334737/376aee64-58cf-11e6-96c0-73528e1364f3.png">

**Comment by chriseth** [comment]
Could you please tell us the browser and version you are using?

**Comment by xavierlepretre** [comment]
Mac OS X 10.11.6 (15G31), Safari Version 9.1.2 (11601.7.7)

In Google Chrome Version 51.0.2704.103 (64-bit), the page works but still yields an error in the console.

**Comment by axic** [comment]
@xavierlepretre is this still happening with the current version?

**Comment by xavierlepretre** [comment]
I still have the same error in Safari Version 9.1.3 (11601.7.8), MacOS 10.11.6 (15G1004).

Google Chrome Version 52.0.2743.116 (64-bit) no longer shows any error, only warnings.

**Comment by axic** [comment]
Okay this is an issue with `ocalStorage` and that your tab is probably missing / corrupted. It seems we iterate `localStorage` keys with `Object.keys(window.localStorage)` which is probably broken.

We should move on to use a proper wrapper, like [`store`](https://www.npmjs.com/package/store).

**Comment by axic** [comment]
@xavierlepretre can you test and report if it is working well?

**Comment by xavierlepretre** [comment]
Still getting `TypeError: null is not an object (evaluating 'text.getLine')`
