### ISSUE TITLE
Logging events causes "TypeError: abi is undefined"

### ISSUE THREAD

**Issue by ethernomad** [ethereum/browser-solidity#170]

**Comment by axic** [comment]
Please be a bit more specific. Regular events work. Indexed or anonymous events probably don't.

**Comment by ethernomad** [comment]
Events don't work at all at the moment. Calling t() triggers the error.

```
contract Test {
    event logit(uint);
    function t(uint i) {
        logit(i);
    }
}
```

**Comment by ethernomad** [comment]
Actually - doing a hard browser reload fixes the issue.

**Comment by bellaj** [comment]
this problem occures if you use the javascript VM however if you change to a local wb3 provider this probleme disappear.
