### ISSUE TITLE
event cannot be called, getting "TypeError: Cannot read property 'event' of undefined"

### ISSUE THREAD

**Issue by evisoup** [ethereum/browser-solidity#171]
getting the following error:
`TypeError: Cannot read property 'event' of undefined`

using this simple SC:
`contract a {
    
    event b(uint c);

    function d(){
        
        b(10);
    }
    
}`

tried the same code on old version of online compiler, and SC worked just fine.

**Comment by axic** [comment]
This code is not producing the above issue, but other cases, such as #115 and #180 are. Those are being fixed.
