### ISSUE TITLE
Large sol file with a contract and libraries - chrome browser error / unresponsive

### ISSUE THREAD

**Issue by ConsentDevelopment** [ethereum/browser-solidity#175]
The solidity-browser produces the following error when compiling large sol files -

   Uncaught JavaScript exception:
   RangeError: Maximum call stack size exceeded

This can be caused be the following -
  
    1. Reaching a max number of functions.
    2. Reaching a max number of events.

The same sol file compiles fine with the Microsoft Edge browser so it looks like a chrome issue.

I need to use Chrome as it supports the Metamask plugin which makes deployment and testing very easy.

**Comment by ConsentDevelopment** [comment]
This issue is not urgent for me as I have got around it by optimizing my contract and libraries and cutting away any functions which are not essential.

**Comment by Denton-L** [comment]
This is also being discussed in #32, although conversation for that seems to have stopped.

**Comment by axic** [comment]
@ConsentDevelopment is this still happening?

**Comment by axic** [comment]
@ConsentDevelopment closing this in favour of #32. Please reopen if it persists.
