### ISSUE TITLE
Simulating sending a balance to and from different addresses

### ISSUE THREAD

**Issue by joshterrill** [ethereum/browser-solidity#178]
I found a video tutorial online walking through the basics of solidity. The contract that they build basically is one where you can send a balance to and from different accounts. I'm trying to figure out how browser-solidity allows you to interact with addresses. Here's my contract so far:

```
contract HelloWorld {
  address public owner;
  mapping (address => uint) balances;
  
  function HelloWorld() {
    owner = msg.sender;
    balances[owner] = 1000;
  }

  function getBalance(address _user) returns(uint _balance) {
    return balances[_user];
  }
}
```

When I press "Create", I get the `getBalances()` field that asks me for `address _user`. When I put in the address that the creation of the contract outputted, `0xca35b7d915458ef540ade6068dfe2f44e8fa733c`, I get an error: `Error encoding arguments: SyntaxError: JSON.parse: expected ',' or ']' after array element at line 1 column 3 of the JSON data`.

Here's a screenshot of what I see:
![Imgur](http://i.imgur.com/ttxiITa.png)

**Comment by phiferd** [comment]
I think you just need to put quotes around the address.

**Comment by joshterrill** [comment]
Yup, I was just going to come back here and say that I figured that out. Is there a way to simulate multiple addresses?

**Comment by chriseth** [comment]
You can select the sender address in the "arrow / paper plane" tab. We are working on adding UI elements to generate new addresses.

**Comment by joshterrill** [comment]
I only see two addresses in there anytime I start up an instance, though. If I switch it from the browser javascript VM to a local testrpc instance, then it shows me all the accounts I have.  But when I switch it from javascript VM to the local instance, the responses to my tests are encoded rather than decoded like they are in the javascript VM, so I've been working in the javasccript VM for right now. Glad to hear that soon there will be a button that allows you to generate multiple addresses. If no one has started working on it yet, let me know. I can probably write it and do a pull request some time in the next day or two.

**Comment by chriseth** [comment]
@axic has started some work on that - I think there is even an open pull request about it.

**Comment by joshterrill** [comment]
Oh okay, cool. Is there a way that browser solidity can emulate sending eth to a contract? I know in the example above, I created a balance manually which is just an int. but can it simulate handling actual eth and moving it around?

**Comment by chriseth** [comment]
Yes, that is what is happeninng in the "VM"  mode.
