### ISSUE TITLE
Save to Disk 

### ISSUE THREAD

**Issue by rolandkofler** [ethereum/browser-solidity#179]
It should be possible to save a source file to disk by pressing a shortcut and or menu item

**Comment by chriseth** [comment]
This is very hard to do because of the browser security framework. Instead, I would prefer saving to github (we should already have an issue for that).

**Comment by axic** [comment]
It could create a ZIP file on-the-fly.

**Comment by chriseth** [comment]
Creating a zip file might be usable for archival purposes, but it is not really a "safe to disk" feature. In general, I would prefer the user interface not to require manual saves at intervals, i.e. there should not be any save button at all.

**Comment by rolandkofler** [comment]
The real problem I'm trying to solve is to use Browser Solidity within GIT projects. How can one work on a JS frontend and use Browser Solidity for the *.sol? For now I copy and past from Browser Solidity to my editor. A custom integration in all possible IDE's would be too big of an effort. The easiest way seemed to save the raw code to disk. But are there alternatives?

**Comment by axic** [comment]
@rolandkofler Github integration is planned (see #153) so that might solve your problem.

However, I do think downloading as ZIP and uploading a ZIP can be useful (and it is possible to do), at least until Github integration is added.

**Comment by rolandkofler** [comment]
More customers for Github. Not that I have something against them, but tools should be open enough to not lock you into a 3rd party. 

I understand: what I really want is **Remix**...!
