### ISSUE TITLE
Solidity library events are not reported correctly in browser

### ISSUE THREAD

**Issue by ConsentDevelopment** [ethereum/browser-solidity#180]
If you use the following solidity library and contract as a example then library events are not being reported correctly in the solidity-browser -

```
library MyLibrary
{
    event event_SomethingHappened(uint32 result, uint256 value);

    function library_function() public
    {
        event_SomethingHappened(6, 3 ether);
    }
}

contract MyContract
{
    function contract_function() public
    {
        MyLibrary.library_function();
    }
}
```

**Comment by ConsentDevelopment** [comment]
Found a workaround for this bug.  All library events have to be duplicated in the calling contract for the events to log correctly.

**Comment by chriseth** [comment]
Which provider (vm, web3 via http, injected web3) did you use?

**Comment by ConsentDevelopment** [comment]
Metamask - https://metamask.io/

**Comment by D-Nice** [comment]
Not to hijack this issue, but events are not working at all for me and other users using https://ethereum.github.io/browser-solidity/
I'm using Javascript VM

Reference to issue in question:
https://github.com/ethereum/browser-solidity/issues/115

Oddly enough, I tried https://chriseth.github.io/browser-solidity/
events work without any issues there.
