### ISSUE TITLE
TypeError: this.detailsOpen is undefined when clicking "Toggle Details"

### ISSUE THREAD

**Issue by D-Nice** [ethereum/browser-solidity#181]
Another TypeError as one gets with events now.

Tried several browsers and different OS's. Some browsers respond differently.

When clicking Toggle Details on any contract, nothing happens, but an error is logged, in Firefox the error comes out as
> TypeError: this.detailsOpen is undefined  -  app.js:105063:65

in Chrome it's

> Uncaught TypeError: Cannot read property 'Ballot' of undefined  -  app.js:105063

As you can see, in the Chrome error it specifies the contract as being undefined.

EDIT: Chriseth's old page does not have this issue.

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/browser-solidity/pull/184
