### ISSUE TITLE
Offline: Provide a zip to make browser-solidity usable offline

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#2]

**Comment by axic** [comment]
How about preparing a zip with each Travis rebuild, which has everything contained (incl. solc)? Such as selfcontained-latest.zip?

The only downside I see is that if someone tries to download it during the time Travis pushes an update, it might be corrupted.

**Comment by chriseth** [comment]
Actually I just realized that we do not keep any history of gh-pages, so we could make travis include the latest version of solc and have the website use that as a fallback. This allows people to just use "file -> save as" in their browser without the need to create a zip.

**Comment by axic** [comment]
Implemented with #129.
