### ISSUE TITLE
Include visual feedback (turning cogs) when code is being compiled

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#201]
The right hand side (where the contract deployment details are) should be cleared at the start of compilation and some visual feedback should be provided while compiling.

**Comment by chriseth** [comment]
The same icon could be used to disable auto-compiling, just as it was in good old cosmo.

**Comment by yann300** [comment]
@axic @chriseth  I think that's quite ok now. please reopen if you feel there room for improvement
