### ISSUE TITLE
Switching compiler version stalls browser

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#212]
This seems to be a regression. Also, the console reports that it loads the compiler without worker.

**Comment by axic** [comment]
For some reason after loading the version (i.e. changing the dropdown twice), the `soljson.compileJSONCallback` (which is the C++ code) never returns.

**Comment by axic** [comment]
It seems to be related to the latest compiler versions. If I start browser-solidity off an earlier version (by specifying the version in the URL) I can keep changing. I'm able to move between 0.2.0 and 0.3.2 without issues. We need to pinpoint the problematic version.

**Comment by chriseth** [comment]
I'm pretty sure the problem appeared around the time the loading mechanism was modified, but that might also be the wrong lead.

**Comment by chriseth** [comment]
As found by @axic, the error comes from the number of reserved function pointers to be exhausted. They seem to be needed for `soljson.Runtime.addFunction` used in solc/wrapper.js. So I suspect this was introduced at the time where we switched from adding the wrapper manually to using the solc npm package.

**Comment by axic** [comment]
We could have a `solc.cleanup()` function to remove those. It is up to the caller to call it though.

**Comment by axic** [comment]
Actually it seems we have a bigger problem there. If an exception occurs in compiler, the pointer isn't freed either.
