### ISSUE TITLE
Previous imports not working any longer

### ISSUE THREAD

**Issue by D-Nice** [ethereum/browser-solidity#227]
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol"; 

Worked fine in contracts before, and now it returns the following error:

Error: Source "github.com/oraclize/ethereum-api/oraclizeAPI.sol" not found: Deferred import
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

**Comment by axic** [comment]
It seems to work for me on Chrome with Solidity 0.4.1. What browser are you using?

**Comment by D-Nice** [comment]
I am using 0.3.6 compiler and earlier, and chrome 47.

**Comment by o0ragman0o** [comment]
I'm getting the same broken import messages also regardless of solc version.  It started when solidity debug highlighting was introduced

**Comment by chriseth** [comment]
I suspect this was starting to fail because the callback format changed with the current line highlighting. It is weird that this is still not working with old compilers now.

**Comment by D-Nice** [comment]
Beside the solidity version, when switching compilers it only says (loading), right after compiler loads, deferred import error if below 0.4.0

Opening console, it shows "Loading version ... without worker" when switching.

**Comment by axic** [comment]
This was working most of the time in my browser, but I could definitely trigger it with having two import statements.
