### ISSUE TITLE
the IDE can not connect the node at localhost to send transactions by  Web3 Provider 

### ISSUE THREAD

**Issue by sportshark** [ethereum/browser-solidity#228]
when using“ web3 provider“ in the environment page , the IDE can not connect the node at localhost to send transactions in Chrome. when press "Create" button  ,the console show errors "Uncaught TypeError: self.txdebugger.web3(...).releaseCurrentHash is not a function" in Chrome。

**Comment by axic** [comment]
I think this was fixed by #231. Please reopen if it persists.
