### ISSUE TITLE
'Transaction Origin' accounts no longer listed in for JavaScript VM so can't deploy to memory

### ISSUE THREAD

**Issue by o0ragman0o** [ethereum/browser-solidity#230]
Since either solc 4 or source level degbugging have been introduced, the accounts drop down 'Transaction Origin', for interacting with the Javascript VM is empty.  Can't deploy to memory. Same behaviour on Chrome and Firefox, Window and Linux...

**Comment by axic** [comment]
What browser is this happening with? It seems to work for me on Chrome.

**Comment by o0ragman0o** [comment]
Tried on Chrome and Firefox on two different computers, Mint 17 and Windows 10. Same failure each time

**Comment by axic** [comment]
I think this was fixed by #231. Please reopen if it persists.

**Comment by o0ragman0o** [comment]
Awesome! Thanks
