### ISSUE TITLE
Clicking warnings/error dialog should scroll in the correct file

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#235]
If multiple files are used in a single compilation run, and the error is in a different file, clicking the error will just jump to the respective position in the master file, and not in the included/imported file.

The correct way to fix this is as follows:

 - disable auto-compilation
 - switch to the correct file (it is part of the error message)
 - scroll to the correct position

**Comment by orgy** [comment]
Seems this has been fixed. Can someone verify? Seems to work as expected on my end.

**Comment by chriseth** [comment]
Oh you are right! Sorry about that!

**Comment by axic** [comment]
I do not think this is fixed since early September. It is a case when using imports and there's an error in the referenced file, clicking on it will not switch tabs.

I do not see any commits in the last 25 days which fixed this?

**Comment by orgy** [comment]
Indeed but upon testing it, it not only switched to the imported file tab, it also scrolled down to where the error is.
