### ISSUE TITLE
Imports chain can't be compiled

### ISSUE THREAD

**Issue by AlKau** [ethereum/browser-solidity#240]
I've got the error **Uncaught JavaScript exception: RangeError: Maximum call stack size exceeded**
On Chrome, Version 53.0.2785.113 m. I use solidity version 0.4.1;

My contracts structure
file A: contract A {} - it is compiled
file B: import "A" contract B {} - it is compiled
file C: import "B" contract C {} - it can't be compiled

app.js:105644 Uncaught RangeError: Maximum call stack size exceeded
isValidError @ app.js:105644
compilationFinished @ app.js:105649
compileJSON @ app.js:105623
(anonymous function) @ app.js:105588
gatherImports @ app.js:105805
compile @ app.js:105583
compilationFinished @ app.js:105667
compileJSON @ app.js:105623
(anonymous function) @ app.js:105588
gatherImports @ app.js:105805

**Comment by chriseth** [comment]
This might be an infinite recursion loop.

**Comment by axic** [comment]
I've tried with 0.4.1 release and latest browser-solidity and it worked without hiccups. It maybe is related to Chrome's issue handling Emscripten.

**Comment by AlKau** [comment]
_Microsoft Edge_ and _FireFox_ also can't compile the file C. 
_Microsoft Edge_ said **Out of stack space** browser-solidity (71926,5);
_FireFox_ doesn't show any error.

**Comment by AlKau** [comment]
I've removed **pragma solidiy ^0.4.1;** from files. And the error is gone.

**Comment by axic** [comment]
Tried this again with Firefox 47.0 and Solidity 0.4.2. Can't seem to reproduce it.

There were some changes in browser-solidity regarding error reporting.

@AlKau Can you please flush your browser cache and retry with the previously affected browsers?

**Comment by ethernomad** [comment]
I can reproduce a very similar problem:

a.sol:
```
pragma solidity ^0.4.2;

import "b.sol";

contract A {}
```

b.sol:
```
pragma solidity ^0.4.2;

import "c.sol";
```

c.sol:
```
pragma solidity ^0.4.2;

contract A {}
```

Compile a.sol. On Firefox the compiler runs for ever. On Chromium it gives:
```
Uncaught JavaScript exception:
RangeError: Maximum call stack size exceeded
```

On the command line it correctly gives:
```
a.sol:3:1: Error: Identifier "A" already declared.
import "b.sol";
^-------------^
```

**Comment by ethernomad** [comment]
Actually it can be reproduced in an much simpler way:

a.sol:
```
pragma solidity ^0.4.2;

import "b.sol";
```

b.sol:
```
pragma solidity ^0.4.2;

import "c.sol";
```

c.sol:
```
pragma solidity ^0.4.2;
```
