### ISSUE TITLE
Values of a new contract are not displayed

### ISSUE THREAD

**Issue by clivebluston** [ethereum/browser-solidity#248]
Using Firefox 47.0.1
Instead we see the following:
TypeError: self.vmTraces[self.processingHash] is undefined

To reproduce just create the following contract and look at the value of number1,2, and 3.

pragma solidity ^0.4.1;
contract owned {
owned public owner;
uint32 public number1 = 0;
uint32 public number2 = 0;
uint32 public number3 = 0;

/\* Constructor */
function owned() {
    owner = owned(msg.sender);
}

modifier onlyOwner {
    if (msg.sender != address(owner)) throw;
    _;
}

function transferOwnership(owned newOwner) onlyOwner {
    owner = newOwner;
}

function getContract() returns (owned contractAddress){
    return this;
}

}

**Comment by axic** [comment]
This is a weird issue because it happens randomly. If you press the button it works.

@yann300 since this is related to remix, can you please check it?

**Comment by axic** [comment]
@yann300 do you have an idea why this could happen?

**Comment by yann300** [comment]
Not sure yet but:
I use the onStep of the vm to compute the trace:
https://github.com/ethereum/remix/blob/master/src/web3Provider/web3VmProvider.js#L76
I need to know which tx is executing at this point so I save the current tx hash in
https://github.com/ethereum/remix/blob/master/src/web3Provider/web3VmProvider.js#L44
in case of a call, everything is ran asynchronously so we cannot rely on `beforeTx` to know what is the context of the `step` event.
One solution might be to do what is done in the cpp client:
do not save the trace at the time of execution but copy the vm state and execute calls/tx on top of the copied state when the user request a debug session.
