### ISSUE TITLE
Add static analysis framework

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#252]
Add a UI framework that can
- display static analysis results, 
- let the user choose which type of analysis to perform

in general, this should allow static analysis modules that share a common interface (usually via the AST) to be selected and run over the source code.

**Comment by chriseth** [comment]
A preliminary PR to achieve something similar is here: https://github.com/ethereum/browser-solidity/pull/107

**Comment by yann300** [comment]
- [x]  Static Analysis framework 
- [ ]  Highlight static analysis tab if warning and trigger a run for each compilation
- [ ]  Display error for each source location
- [ ]  Display 'No Warning' if no Result
