### ISSUE TITLE
Combine tabs "environment" "transaction" and the dapp-ui

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#254]
It is weird that the dapp ui is shown for all tabs, some of them are only concerned with the source code or take a lot of space.

- [ ] Combine transaction settings and dapp UI into a single tab.
- [ ] Errors will also go into the dapp UI tab (it shows red if there is an error).
- [ ] dapp UI should show a single line containing the compiler version (not the full compiler selector)
- [ ] Combine compiler settings and provider selection

**Comment by chriseth** [comment]
Identified the following areas:

 - settings: break lines, use injected web3 by default
 - file management: publish gist, import gist, import from github, copy files (might move to the file tree view alltogether)
 - compilation / code editing: auto-compile  / compile button / errors / warnings / static analysis
 - execution / trying out contracts: transaction settings, provider selection, dapp-ui
 - debugger
 - formal verification

**Comment by ninabreznik** [comment]
We also mentioned to **replace icons for titles** of each of the tabs
