### ISSUE TITLE
Change 'upload' button to 'add (local) file' button

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#256]
The "upload" button (top left corner) is a bit misleading: It does not upload anything, it just imports a local file into the browser, so it should rather look like a document with a plus sign.

**Comment by axic** [comment]
I can two good alternatives are:
- "Open local file": http://fontawesome.io/icon/folder-open-o/
- "Add new file": http://fontawesome.io/icon/plus-square-o/

**Comment by chriseth** [comment]
I think the folder is the better of those two.

**Comment by axic** [comment]
Yep, that was my first choice too. Couldn't find better icons in FA.
