### ISSUE TITLE
Fix browser testing

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#263]
Browser testing should be smooth and always working. We are currently not at this stage and the assumption is that loading the compiler takes too much memory on the testing machines.

One solution would be to pre-define all compiler calls that will be done in all tests and run them via soljson once on travis (i.e. in the node environment) before the actual selenium / sauce labs tests are run and then substitute soljson.js with a mock compiler at test time. For that, we can use the url `https://localhost/browser-solidity/#version=builtin` - but that seems to have a bug, we should also solve that.

**Comment by axic** [comment]
Fixed in #273.
