### ISSUE TITLE
Intrinsic gas too low caused by estimateGas function

### ISSUE THREAD

**Issue by jordanmurkin** [ethereum/browser-solidity#264]
After experiencing a problem on a large project I was working on, I created a simplified market contract to test a basic principle of my system. This basic code can be found here: https://gist.github.com/jordanmurkin/1ac2b18ff093d45856cea125063b7e41

In this contract, it will compile correctly and work correctly when using the JavaScript VM. When instead using a Web3 Provider from a geth node on my localhost, the buy function will return "Error: Intrinsic gas too low" when attempting to "buy" a Sale in the market mapping that has been created (it will not throw this error when attempting to "buy" from a non-existing saleId, I'm not sure why). This only happens through browser-solidity, as when using the same contract directly through the geth console it will also work correctly.

Because of this I think it is a problem in the way gas is estimated in browser-solidity when a function doesn't require much gas. I altered the current code (starting at line 108617):

```
self.web3.eth.estimateGas(tx, function (err, resp) {
        if (err) {
          return cb(err, resp);
        }

        if (resp > gasLimit) {
          return cb('Gas required exceeds limit: ' + resp);
        }

        tx.gas = resp;

        ...
```

to (to always send the gasLimit with the sendTransaction):
```
self.web3.eth.estimateGas(tx, function (err, resp) {
        if (err) {
          return cb(err, resp);
        }

        if (resp > gasLimit) {
          return cb('Gas required exceeds limit: ' + resp);
        }

        tx.gas = gasLimit;
        
        ...
```

With this change it works completely fine through browser-solidity, thus I think there may be a problem with the estimateGas function. I also think this solution provides more control to users, as the amount of gas they specify in the UI is then the actual amount of gas sent with the transaction.

**Comment by axic** [comment]
Thank you for looking into this. The `gasLimit` is the value you can set in browser-solidity (the second tab on the top right).

We're calling `estimateGas` to figure out the actual cost. I think the real solution here would be adding an option for the user to override estimateGas.

**Comment by axic** [comment]
Can you please tell what geth version you're using what value is estimateGas returning for you? It may need to be reported to go-ethereum.

**Comment by jordanmurkin** [comment]
It turns out it was my own fault. My geth version was not fully up to date, you asking me to check it made me quickly update just to make sure (I only updated last week so I just thought it was OK before). Apologies for raising the issue wrongly, I'll close it.
