### ISSUE TITLE
import via ipfs

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#274]
Importing files via ipfs should work in the same way as importing via github. Suggested format:
`ipfs://<hash>/path/inside/structure.sol`

Things to investigate:

- [ ] can we use gateway.ipfs.io for that?
- [ ] does it support CORS?

**Comment by axic** [comment]
"Duplicate" of #133 :)

> `ipfs://<hash>/path/inside/structure.sol`

IPFS folks actually prefer `/ipfs/<hash>..` or `/ipns/<hash>` notation. See also https://github.com/ipfs/go-ipfs/issues/1678.

**Comment by chriseth** [comment]
Ah I knew it sounded familiar :-)
`/ipfs/` is also fine.
