### ISSUE TITLE
Consensys' HumanStandardToken won't compile

### ISSUE THREAD

**Issue by ramvi** [ethereum/browser-solidity#276]
[The project](https://github.com/ConsenSys/Tokens) builds and works fine in terminal, but in browser-solidity i won't compile.

Chome returns
```
Uncaught JavaScript exception:
RangeError: Maximum call stack size exceeded
```

Firefox doesn't report anything back.

The weird thing is that HumanStandardToken doesn't add that much more code than what's already in StandardToken which it includes. What in HumanStandardToken makes browser-solidity stop compiling?

**Comment by ramvi** [comment]
It works when removing the top multi line comment. Weird:
```
/*
This Token Contract implements the standard token functionality (https://github.com/ethereum/EIPs/issues/20) as well as the following OPTIONAL extras intended for use by humans.

In other words. This is intended for deployment in something like a Token Factory or Mist wallet, and then used by humans.
Imagine coins, currencies, shares, voting weight, etc.
Machine-based, rapid creation of many tokens would not necessarily need these extra features or will be minted in other manners.

1) Initial Finite Supply (upon creation one specifies how much is minted).
2) In the absence of a token registry: Optional Decimal, Symbol & Name.
3) Optional approveAndCall() functionality to notify a contract if an approval() has occurred.

.*/
```

**Comment by chriseth** [comment]
Maybe related: #240 #32 #175 - you might want to try a different browser, too.

**Comment by axic** [comment]
@ramvi can you please retry this with the latest browser-solidity and compiler version 0.4.4?

Also in different browsers (Firefox and non-Firefox).

**Comment by ramvi** [comment]
The bug still exist: http://ethereum.github.io/browser-solidity/#version=soljson-v0.4.4-nightly.2016.10.26+commit.34e2209b.js&gist=f78d8fe72e8d3e102fbbd5233c354766

Remove the comment on the top of HumanStandardToken.sol and it works.

**Comment by axic** [comment]
I get a different error on Firefox:
```
Uncaught JavaScript exception:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Comment by axic** [comment]
I think this might be an issue with the ACE editor.

**Comment by axic** [comment]
@ramvi in your case though, which I was able to reproduce somewhat (not getting the error, but it keeps looping to compile) is very likely a bug in `gatherImports`.

**Comment by chriseth** [comment]
Please check if this is fixed now.

**Comment by ramvi** [comment]
Amazing
