### ISSUE TITLE
VM Error: toString() of undefined during contract creation

### ISSUE THREAD

**Issue by Niklas345** [ethereum/browser-solidity#281]
1) Load the example contract(Ballot). Should compile without problems.
2) With enviroment set to JavaScript VM, usage of "Create" is not possible, instead returns the following error: VM Exception: TypeError: Cannot read property 'toString' of undefined

Tested on two devices, reproduceable with these steps. Tested in Chrome, Firefox and Edge. Both devices were Windows 10.

**Comment by axic** [comment]
Thanks! This is being fixed right now, should be back soon.

**Comment by axic** [comment]
Fixed now.
