### ISSUE TITLE
Integrate blockchain support for the VM mode

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#294]
In order to retrieve txs after execution. Now we need to save them in a separate structure
https://github.com/ethereumjs/ethereumjs-lib/blob/master/docs/blockchain.md

**Comment by axic** [comment]
@yann300 didn't you implement this?

**Comment by yann300** [comment]
Not completely I think. My idea was to use 
https://github.com/ethereumjs/ethereumjs-lib/blob/master/docs/blockchain.md
together with the VM, this is not yet done.
