### ISSUE TITLE
File Persists After Deletion

### ISSUE THREAD

**Issue by Denton-L** [ethereum/browser-solidity#30]
# Bug
If you have a file called 'Untitled<N>', where <N> is either an empty string or an integer, if you delete it and create a new 'Untitled<N>' of the same name, the new file will not be blank but instead, will contain all of the content from the old file.

## Reproduction
1. Open up a new instance of browser-solidity.
2. Press the New File button and make some changes to the file, 'Untitled<N>'.
3. Delete 'Untitled<N>'.
4. Press the New File button again to create a new file with the same name.
5. The old changes prior to deletion should be displayed in the new file.

## Browser
Chromium Version 50.0.2661.102 (64-bit)

**Comment by redsquirrel** [comment]
I've seen this too.
