### ISSUE TITLE
gh-pages branch: constant function call is send as transaction

### ISSUE THREAD

**Issue by Subby83** [ethereum/browser-solidity#300]
When a simple contract is deployed, the constant functions are marked correctly in blue color.
But when a function is clicked the client sends a transaction to the ethereum node.

Also on deployment of the contract there is the following text next to each constant function:
"Waiting for transaction to be mined"

I am connected to a running ethereum node via Web3 Provider.

So problem seems to be that constant functions are not triggered with eth_call but with eth_ sendTransaction.

**Comment by zwsyff888** [comment]
UniversalDApp.prototype.runTx = function (args, cb) {
  var self = this
  var tx = {
    to: args.to,
    data: args.data,
    useCall: args.useCall
  }
