### ISSUE TITLE
Cannot load "latest local version"

### ISSUE THREAD

**Issue by chfast** [ethereum/browser-solidity#309]
The "latest local version" cannot be loaded because the app tries to load `file:///.../browser-solidity/index.html/soljson.js` instead of `file:///.../browser-solidity/soljson.js`.

**Comment by axic** [comment]
This was broken by #277.

Solutions:
- remove `index.html` from the pathname (this will make it work if accessing through HTTP, but without access to github.io)
- don't do the location parsing when on `file://`

**Comment by chriseth** [comment]
We should check whether the path ends in `/` or not.
