### ISSUE TITLE
State variables not visible "At Address"

### ISSUE THREAD

**Issue by TbLtzk** [ethereum/browser-solidity#319]
Hello,
I've created this contract and deployed this contract to morden testnet: https://ethereum.github.io/browser-solidity/?gist=0a2acac5d68d558a0f2a8ac944ef87f2

The contract sits here and seems all right:
https://testnet.etherscan.io/address/0xc0771e9af291f4378141bec751d089348d19aba9.

But if I load the contract address via "At Address", the state variables are all undefined.
![image](https://cloud.githubusercontent.com/assets/8383712/20140858/c6785644-a68d-11e6-8638-e8044b2f0be7.png)

I'm using injected web3 via metamask plugin:
![image](https://cloud.githubusercontent.com/assets/8383712/20224680/eefa961e-a83f-11e6-9a7f-5d98adf4e01b.png)

**Comment by hrishikeshio** [comment]
+1

**Comment by axic** [comment]
@TbLtzk can you check it again? I think #318 fixed this.

**Comment by TbLtzk** [comment]
Hmm, #318 was merged 4 days ago and I reported the issue 3 days ago. Has there been a deployment in between?

**Comment by TbLtzk** [comment]
No, Issue is still reproducible with the current version.
