### ISSUE TITLE
Public variables throw js error

### ISSUE THREAD

**Issue by zmitton** [ethereum/browser-solidity#320]
When i try something like:

    pragma solidity ^0.4.4;
    contract Test{
    address public owner;
        function Test(){
            owner = msg.sender;
        }
    }

in vm mode the variables say "waiting for tx to be mined" next to them and I see this js error:
`Uncaught TypeError: cb is not a function(…)`

**Comment by hrishikeshio** [comment]
+1. It has made solidity-browser unusable.
