### ISSUE TITLE
Recent constructor issue when using Browser Solidity + Metamask

### ISSUE THREAD

**Issue by jdetychey** [ethereum/browser-solidity#334]
Hi there, I've been coding in Browser Solidity and deploying with Metamask for months (on Morden), I love those tools congrats to the dev teams. Recently I have experienced a strange issue, when I deploy a contract the variables that are supposed to be defined by my constructor get "Value: undefined". 

See for example:

`pragma solidity ^0.4.4;`
`contract test {`
`address public owner;`
`function test() {`
`owner = msg.sender ;`
`}`
`}`
at address: 0x706c33a0a5b70db94886fc6b3f5e3a86a5665a3e (morden)
owner Value: undefined Decoded: address: 0x0

Did I miss something? (cross post from /r/ethdev/ )

**Comment by yann300** [comment]
it might be related to https://github.com/ethereum/browser-solidity/issues/248
