### ISSUE TITLE
Readonly tabs

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#344]
When importing sources from github or swarm, it is useful to be able to display them. For that, read-only tabs should be available.

**Comment by axic** [comment]
It seems that ACE only supports setting the editor to readonly and not the sessions (i.e. the tabs). Too bad it can only be implemented as a workaround, setting the editor to readonly when the readonly tab is selected.

**Comment by chriseth** [comment]
I'm not sure I understand what you mean by "setting the tabs to readonly". The tabs are implemented by ourselves and the session is an internal object not modifyable by the user. The idea of this story is that it should be possible to display files which cannot be modified by the user.

**Comment by axic** [comment]
Depends on #384.
