### ISSUE TITLE
Display payable functions uniquely

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#349]
Currently we have three button colors:
- green: attach to address
- red: transact
- blue: call

We could split red into two:
- light red: transact (non-payable)
- deep red: transact (payable)

Alternatively we could have a different border color for payable transact buttons?

@yann300 @chriseth any other suggestions?

**Comment by yann300** [comment]
yeah light red and deep red is fine.
I also think it could make sense to move the `value` input from the second tab to each transaction row.
so the input will be shown only if the function is payable

**Comment by chriseth** [comment]
I think that the colors will appear mostly weird to the users, but yeah, different shades of red is probably a good idea. Perhaps we can decrease the saturation of the button colours in general.

**Comment by axic** [comment]
> I also think it could make sense to move the value input from the second tab to each transaction row.

That would be nice, but the space is quite limited. Probably it would make sense redesigning the interface a bit.
