### ISSUE TITLE
decrease gas in web3 deploy script

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/browser-solidity#350]
I tried deploying a contract that I compiled in the browser-solidity compiler and (after removing linebreaks) copy-pasted into the geth console. (latest geth version) This left me with the following error:
```Error: Exceeds block gas limit undefined```
When reducing the default gas amount of 4700000 to 300000 things worked out well. I guess the default value is too high and should be reduced?

**Comment by yann300** [comment]
yes the gas limit is 4003902 at the moment. We should use the value of the second tab

**Comment by yann300** [comment]
done
