### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by milyInzhoop** [ethereum/browser-solidity#359]
at "npm run build" fails.

here the log:

> 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild browser-solidity@0.0.0
6 info build browser-solidity@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info browser-solidity@0.0.0 Failed to exec build script
9 verbose stack Error: browser-solidity@0.0.0 build: `mkdir -p build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid browser-solidity@0.0.0
11 verbose cwd D:\Projects\BrowserSolidity
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error browser-solidity@0.0.0 build: `mkdir -p build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js`
17 error Exit status 1
18 error Failed at the browser-solidity@0.0.0 build script 'mkdir -p build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js'.
18 error This is most likely a problem with the browser-solidity package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     mkdir -p build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js
18 error You can get their info via:
18 error     npm owner ls browser-solidity
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

> 

What am I doing wrong?

**Comment by axic** [comment]
@milyInzhoop can you please retest with latest `master`?

**Comment by milyInzhoop** [comment]
same error

**Comment by milyInzhoop** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild browser-solidity@0.0.0
6 info build browser-solidity@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info browser-solidity@0.0.0 Failed to exec build script
9 verbose stack Error: browser-solidity@0.0.0 build: `mkdir build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid browser-solidity@0.0.0
11 verbose cwd D:\Projects_Inzhoop\BrowserSolidity
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error browser-solidity@0.0.0 build: `mkdir build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js`
17 error Exit status 1
18 error Failed at the browser-solidity@0.0.0 build script 'mkdir build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js'.
18 error This is most likely a problem with the browser-solidity package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     mkdir build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js
18 error You can get their info via:
18 error     npm owner ls browser-solidity
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by axic** [comment]
@milyInzhoop would you be able running those commands separately to find out which one is breaking?

- `mkdir build`
- `browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]`
- `babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js`

**Comment by milyInzhoop** [comment]
1)
"mkdir build; browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]; babel --plugins=transform-es2015-template-literals build/app.js --out-file build/app.js   "

-> syntax error

2) mkdir build --> OK
browserify src/index.js -g yo-yoify -o build/app.js -t [ babelify ]  --> "browserify" not recognized as command..
