### ISSUE TITLE
Problem setting uint value to zero

### ISSUE THREAD

**Issue by PietroR91** [ethereum/browser-solidity#368]
I made a little smart contracts with solidity browser, This is my code:

```
pragma solidity ^0.4.0;

contract Test {
    struct User {
        string name;
        string surname;
        uint active;
    }

    mapping(bytes32 => User) public userRegister;

    function add_user(string _name, string _surname) {
        bytes32 _hc=sha3(_name, _surname);
        User p = userRegister[_hc];  

        p.name=_name;
        p.surname=_surname;
        p.active=1;
    }

    function remove(string _name, string _surname)  {
        bytes32 _hc=sha3(_name, _surname);
        userRegister[_hc].active=0;  
    }

    function active(string _name, string _surname)  {
        bytes32 _hc=sha3(_name, _surname);
        userRegister[_hc].active=1;  
    }
}
```
When I use "JavaScript VM" everything's fine, but when I compile the contract with Injected Web3 there is a problem.

Adding a user (with add_user) it's all okay, but when i try to remove a user, i get an error: callback contain no result Error: Out of gas

After some test i supposed that error is given when I try to set a uint value to zero.

Then I try to change the 0 in
`userRegister[_hc].active=0;`
with 9(or other int number)
`userRegister[_hc].active=9; `

And all works fine.

**Comment by chriseth** [comment]
This seems like a problem with the gas estimation functionality of the backend node you are using. Which one is it? geth?

**Comment by fabioberger** [comment]
I've just encountered this issue as well and can confirm that this is indeed an issue with geth's gas estimation functionality. Will open an issue with go-ethereum.

**Comment by axic** [comment]
@fabioberger thanks!

@PietroR91 can we close this issue?

**Comment by PietroR91** [comment]
Yes, it can be closed! Thanks
