### ISSUE TITLE
Contract needs to be linked to a library, this is only supported in the JavaScript VM for now.

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/browser-solidity#37]
Context: https://github.com/ethereum/browser-solidity/blob/master/src/universal-dapp.js#L397

Is there any reason why this can't or shouldn't be supported when in __Web3 Provider__ mode? I'm working on library support and could investigate this.

**Comment by chriseth** [comment]
I think the main problem is that you have to wait for the library to be deployed to be sure about the contract address.

**Comment by redsquirrel** [comment]
Regarding the web3 execution context, this part of the software feels like it was started but left unfinished. As shown in #43, it's possible to use some of the existing code that works in the VM execution context in order to link/deploy to web3. But more work will be required in order to get it fully functional in web3. Before I push in that direction, I'm curious if @chriseth is open to it.
