### ISSUE TITLE
Create browser-solidity configuration

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#374]
It should be a JSON file named `.browser-solidity.json` as stored in the same storage layout as other files. Potentially it should be hidden in the editor.

The `editorSize` settings should move into this configuration. In the future it could also hold other variables such as auto-compilation is enabled or not.

Benefit: simple configuration file which can be saved and reloaded together with other files and/or gists.

**Comment by chriseth** [comment]
I don't really see the benefit in having this two-layer abstraction for the settings. What about `localStorage['settings']['editorSize']`?

**Comment by axic** [comment]
Each localStorage entry is a string, you cannot have `localStorage['settings']['editorSize']`. Will it automatically JSONify it?

The benefit is it can downloaded using the download feature, chrome would synchronize it and also gists could contain it.

**Comment by axic** [comment]
Also: we could move all the settings we have in the URL hash into this file and save it to gists. That would mean only the gist hash is needed to load a gist with all the original settings.

**Comment by axic** [comment]
Heh, I had opened a similar issue #150 a while ago.

**Comment by axic** [comment]
Implemented by #375.
