### ISSUE TITLE
"copy files" does not work

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#394]
The "copy files" feature that can be used to copy files from different browser-solidity deployments fails due to the error "TypeError: divStyle is null".

This feature loads the other website inside an iframe and then forwards the data via some javascript interface. It might be that this has disappeared with the refactorings.

**Comment by yann300** [comment]
please retry, that works for me

**Comment by chriseth** [comment]
Yep, seems to be fixed!
