### ISSUE TITLE
Default account for custom Web3 provider

### ISSUE THREAD

**Issue by Grety** [ethereum/browser-solidity#421]
How would you configure default account to connect to a private network when selecting "Web provider" on environment tab and define custom Web3 provider endpoint?
I keep getting `Invalid RPC response ""` although my miner (and RPC endpoint) is functioning properly

**Comment by yann300** [comment]
are you using geth?
with the following parameter?
--rpc --rpcapi web3,eth,debug,net

**Comment by Grety** [comment]
Thanks a bunch! I was missing `debug` api. Besides I noticed I had CORS problems while working in Solidity-browser from my local web server. [This](http://ethereum.stackexchange.com/a/9637/4853) also helped
