### ISSUE TITLE
Browser Solidity no longer compiles

### ISSUE THREAD

**Issue by chejazi** [ethereum/browser-solidity#430]
If I access remix.ethereum.org, the default contract no longer shows up in the editor any anything I type into the editor does not get compiled (with auto-compile enabled or when I hit "compile")

It was working fine as of a few days ago.

Confirmed not working on Chrome, Firefox, & Safari on my OSX laptop.

**Comment by chriseth** [comment]
Thanks for reporting, this looks really severe!
