### ISSUE TITLE
 Failed to decode output: Error: Invalid offset: 0 On any value

### ISSUE THREAD

**Issue by tuytuy** [ethereum/browser-solidity#431]
I cannot seem to access values stored in contracts.
I have been trying to follow up the tutorial here: https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-consortium-blockchain-network
all works fine until I actually interact with a contract, I can commit it to the chain but the values just don't show up. Here is a print screen:

![image](https://cloud.githubusercontent.com/assets/6547517/23098576/69a64df2-f649-11e6-880e-5e03e0a05e1a.png)

**Comment by yann300** [comment]
are you using geth as backend or the javascript VM?

**Comment by tuytuy** [comment]
I am using the Azure VM template that you can find here: https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-consortium-blockchain-network
Which is using Geth backend I think.

**Comment by yann300** [comment]
Here something that could be useful:
https://github.com/Azure/azure-quickstart-templates/pull/3100
I think the issue will be fixed by https://github.com/ethereum/go-ethereum/issues/3653

I close, please reopen if you need so
