### ISSUE TITLE
Transaction receipt?

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/browser-solidity#444]
Is it possible to see the transaction receipt? If not, can you expose it?

**Comment by axic** [comment]
There's a transaction receipt only in RPC mode. What would you use it for?

**Comment by axic** [comment]
Probably it would make more sense exposing a debug log which shows all transactions, including all RPC request/responses.

**Comment by aakilfernandes** [comment]
Hey, I needed it to read event logs. I'm no longer having the issue, so you can close if its not a planned feature.
