### ISSUE TITLE
Error decoding returned dynamic array of arrays with 2 members.

### ISSUE THREAD

**Issue by KingOfAllChunks** [ethereum/browser-solidity#446]
Hello. I'm using the http://remix.ethereum.org browser solidity, with solidity version 0.4.9.

Let's say that I have the following method in my contract: http://pastebin.com/DAT94Gn4

When called from browser solidity and it's interal Javascript VM, the result is this:
`Value: "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
Transaction cost: 23933 gas. (caveat)
Execution cost: 2661 gas.
Decoded: Failed to decode output: TypeError: Cannot read property '1' of null`

If calling from the same interface, but connecting to a local RPC node instead, the result is the same.

What is this issue? Is there a way I can return a dynamic array of pairs of uint128s that will work? I don't want to make 2 methods to extract this data.

**Comment by chriseth** [comment]
@yann300 are you working on this?

**Comment by yann300** [comment]
yes that's https://github.com/ethereumjs/ethereumjs-abi/pull/41
