### ISSUE TITLE
Geth 1.5.8 only returns 0, JSON-RPC API fails

### ISSUE THREAD

**Issue by Metaception** [ethereum/browser-solidity#457]
JSON-RPC API seems to have changed between 1.5.7 and 1.5.8.

RPC calls to geth 1.5.8+ now always returns zero.

See [this](https://ethereum.stackexchange.com/questions/13018/geth-1-5-8-only-returns-0/13034#13034) for BokkyPooBah's analysis

**Comment by yann300** [comment]
it might be related to that:
https://github.com/ethereum/go-ethereum/issues/3653

could you post the screenshot where remix does not diplay the correct value?

**Comment by Metaception** [comment]
I tested this simpleStorage code:

    pragma solidity ^0.4.2;
    
    contract simpleStorage {
    	uint storedData = 4;
    
    	function set(uint x) {
    		storedData = x;
    	}
    
    	function get() constant returns (uint retVal) {
    		return storedData;
    	}
    }

Here is my geth command:

    geth --dev --mine --rpc --rpccorsdomain "*" --datadir dev

The **get()** function should return 4, but it always returns 0 in versions 1.5.8 and 1.5.9

**Comment by Metaception** [comment]
Doesn't seems to be the same issue as [ethereum/go-ethereum#3653](https://github.com/ethereum/go-ethereum/issues/3653)

I tested with a new chain, not a old one.
The result was also: 
```
Value: "0x"
Decoded:
    uint256 retVal: 0
```
Not a error like that one.

Interestingly, it appears that running the code in the JS console works fine.

**Comment by yann300** [comment]
I tried with 1.5.8, I can reproduce,
this is related to the gas estimation (the value returned by web3.eth.estimateGas is too low).
so I am pretty sure it is related to https://github.com/ethereum/go-ethereum/issues/3653 .
