### ISSUE TITLE
"create" button disabled

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/browser-solidity#474]
I'm trying to deploy the "GiftableToken" contract but its disbaled

http://imgur.com/a/nnHo1

https://gist.github.com/anonymous/888b4c16a560f8799ac92e865a09e10c

**Comment by aakilfernandes** [comment]
When I hover over it, theres a circle with a line through it

**Comment by axic** [comment]
Likely `GiftableToken` is an abstract contract. Ensure that every required function is implemented. 

There's a pending issue for the compiler to report all non-implemented functions.

**Comment by aakilfernandes** [comment]
I dont think thats it. I can deploy HumanStandardToken, and GiftableToken implements HumanStandardToken.

**Comment by aakilfernandes** [comment]
And gets fixed if I downgrade to solidity 0.4.4. Maybe its a solidity issue?

**Comment by axic** [comment]
Well it doesn't seem to be a problem in Remix, but Solidity (if it is really not an abstract contract):

```
$ solc/solc --bin GiftableToken.sol 
Warning: This is a pre-release compiler version, please do not use it in production.

======= GiftableToken.sol:GiftableToken =======
Binary: 


======= HumanStandardToken.sol:HumanStandardToken =======
Binary: 
6060604052604060405190810160405280600481526020017f48302e3100000000000000000000000000000000000000000000000000000000815250600690805190602001906200005292919062000139565b5034156200005c57fe5b604051620011cd380380620011cd833981016040528080519060200190919080518201919060200180519060200190919080518201919050505b83600060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550836002819055508260039080519060200190620000f992919062000139565b5081600460006101000a81548160ff021916908360ff16021790555080600590805190...
```

**Comment by aakilfernandes** [comment]
Cool. I'll migrate over there. Thanks!
