### ISSUE TITLE
Publish button should have "title"

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#483]
The use of the publish button as it is is not really obvious to a user. There should be at least a title text that mentions that the metadata of the contract is published to a swarm node, and not the contract itself.

**Comment by axic** [comment]
> that mentions that the metadata of the contract is published to a swarm node, and not the contract itself.

Both are published.

**Comment by chriseth** [comment]
Ah, confusion already :-)
So we should put the following into the title: The metadata and the source code is published to swarm, the contract is not deployed to the blockchain.

**Comment by yann300** [comment]
and also put the bzz url of the metadata file after having published it.
What is the difference between this published metadata and the `Metadata location` off the right panel under the compilation result?

**Comment by axic** [comment]
It is the same. The one on the right is calculated by Solidity as is part of the bytecode. As part of the "publish" it also verifies that the published has matches and will complain otherwise.

**Comment by yann300** [comment]
ok so the one on the right will be available after the publish button is pressed right?

**Comment by axic** [comment]
Yep, that will be the hash on Swarm (if everything goes according to plan) 😉
