### ISSUE TITLE
Gists "double load" on refresh

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/browser-solidity#487]
1. Go to https://ethereum.github.io/browser-solidity/#version=soljson-v0.4.10+commit.f0d539ae.js&gist=ea236029aacdd5a6b443d6a82905f2c8
2. Refresh the page

All the contracts will have been loaded twice (there will be a "Thank.sol" and a "Thanks.sol1")

**Comment by yann300** [comment]
that story should fix this:
https://github.com/ethereum/browser-solidity/issues/487
