### ISSUE TITLE
Gas limit for injected web3 provider

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/browser-solidity#488]
Hey,

Not 100% sure, but it looks like the gas limit is being set at the block gas limit, even when using injected web3 provider. I'm using remix to interact with the real chain, so it would be nice to either leave the gas limit empty, or some minor multiple over the estimate gas

**Comment by yann300** [comment]
yes, 
we need to do something about that cause the `gasLimit` input is not used anymore when interfacing with an external node
https://github.com/ethereum/browser-solidity/blob/master/src/app/txRunner.js#L80

**Comment by yann300** [comment]
fixed: gaslimit is reused now. please reopen if you still have the issue
