### ISSUE TITLE
auto disable `autocompile` if compilation performance too low

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#489]

**Comment by yann300** [comment]
I would like to disable `autocompile` by default every time.
@chriseth ?
then we'll replace the compilation result by a warning saying the `autocompile` is off.
Cause I received feedback that remix is pretty slow if there are multiple 'opened' files.

**Comment by chriseth** [comment]
Yes, that's a good idea. Perhaps the warning should rather be put where the compile button is. We should also have an indication that the compiler is currently compiling.

**Comment by yann300** [comment]
add a key shortcut for compilation
