### ISSUE TITLE
Record Transaction

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#490]
Module that records transactions and save them as JSON; then stored in the browser storage and/or gist

**Comment by chriseth** [comment]
Is this the "scenarios" feature?

**Comment by yann300** [comment]
kind of yes, this issue would be more focused in the "recording" module that we'll use to build scenarios

**Comment by axic** [comment]
I suggest the following:
- `TxLog.reset(<project>)`
- `TxLog.append(<project>)`

It would safe to a JSON called `<project>/txlog.json`.

**Comment by yann300** [comment]
Here is a set of proposed PRs:

 1) A light module that:
  - Listen on the `TransactionInitiating` event ( still to be added there https://github.com/ethereum/browser-solidity/blob/master/src/universal-dapp.js#L537 )
  - Keep a list of recorded transaction in a map (key would be a timestamp)
  - The list is reset when execution context change ( ExecutionContext::contextChanged )
  - Each entry in the map contains: from / to / value / gas / data (basically same as web3.sendTransaction expect ( https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction ) )
  - Real addresses should be translated into token (apply to: to / from / return value of contract creation)
  e.g: from: 0x123...123 , to: 0x123...145 should be saved as: from:<account1>, to:<account2> 
  e.g: from: 0x123...123, to: null (cause this is a contract creation), the return value is the address of the created contract.
(note: translating input parameters should maybe not be included in this PR).
 - The run `button` will provide a `copy ran transactions` action that'll copy to the clipboard a stringify json value of the saved map.

**Comment by yann300** [comment]
UPDATE: @serapath as you said also,
It might be interesting at some point to plug the recorder to the terminal, so we can record transactions created from the outside (that would mean listening on `TxLogger`)

**Comment by yann300** [comment]
2) New action in the run tab:
 - Display in a modal content editable input to paste the json map exported above.
 - Run action will use `UniversalDApp::runTx` to execute sequentially all the transactions. The `asynce.waterfall` should be overriden in that case cause we already have the needed input.
 - Basically, transaction from / to tokens will be resolved as follow:
if (start with 0x) do nothing (we already have a supposed address)
if not : <account - 0> is resolved to the first account in the list of accounts given from universaldapp.
<account - 1> is resolved to second first account in the list of accounts given from universaldapp.
if the account list is not large enough, we take the last one.
 - at each callback call, if the transaction succeed and if this is a creation transaction, we should call runtab.addInstance( ... ) which basically do:
`instanceContainer.appendChild(appAPI.udapp().renderInstance(contract, address, selectContractNames.value))`

**Comment by serapath** [comment]
```js
var copy2clipboard = require('copy2clipboard')
var modal = require('modal')
var recorder = require('recorder') // singleton?
var translate = require('translate') // what to apply this to and why and how does it work?
/*
  Basically, transaction from / to tokens will be resolved as follow:
  if (start with 0x) do nothing (we already have a supposed address)
  if not : <account - 0> is resolved to the first account in the list of accounts given from universaldapp.
  <account - 1> is resolved to second first account in the list of accounts given from universaldapp.
  if the account list is not large enough, we take the last one.
*/
var button = document.querySelector('#copyRunTransactions')

udap.register('TransactionInitiating', record)

function record (tx) {
  var { from, to, value, gas, data /*, gasPrice?, nonce? */ } = tx
  var timestamp = new Date() // or some other way?
  /*
    Real addresses should be translated into token (apply to: to / from / return value of contract creation)
    e.g: from: 0x123...123 , to: 0x123...145 should be saved as: from:, to:
    e.g: from: 0x123...123, to: null (cause this is a contract creation),
    the return value is the address of the created contract.
    @TODO: what does it mean?
  */
  from = translate(from)
  to = translate(to)
  var record = { from, to, value, gas, data /*, gasPrice?, nonce? */ }
  recorder.append(timestamp, record)
}

executionContext.register('contextChanged', function () {
  recorder.reset()
})

button.onclick = function (event) {
  var txArray = JSON.stringify(recorder.getAll())
  copy2clipboard(txArray)
  modal.show(txArray)
}

runButton.onclick = function (even) { // on modal OR run tab
  var txArray = JSON.stringify(recorder.getAll())
  udapp.runTx(txArray, callback)
  // OR
  txArray.forEach(tx => udap.runTx(tx, callback))
}

function callback () {
  /*
    at each callback call, if the transaction succeed and if this is a creation transaction, we should call 
    runtab.addInstance( ... ) which basically do:
    instanceContainer.appendChild(appAPI.udapp().renderInstance(contract, address, 
    selectContractNames.value))
  */
}

**Comment by yann300** [comment]
Please could you put that in a branch + PR ? that is easier that way to comment.
I think what you wrote is ok. 
the 1) and 2) should be two different PRs, so could you include for now only 1) in your proposal ?

_For the translation part:_ 
you can't keep original addresses when you save the transaction. 
1) so instead of saving:
`from: 0x123...123, to 0xabc...abc `
we should save;
`from: <account -1>, to <account - 2>`
because transactions will be replayed in an another context where addresses are different.

2) if `to` is null, that means we have a contract creation. in that case, we should:
 - wait for the return value of that transaction (the return value is the new contract address , let's say A1) - A1 is hex.
 - map the new address (A1) to <contract - (name) - 1>.
 - when a transaction call is made, if `to` is A1 , set `to` to <contract - (name) - 1>.

**Comment by yann300** [comment]
Well the `initiatingTransaction` should also have a time stamp (this could be the one to use in the record also), so we can retrieve the result (`transactionExecuted`) of initiated transaction easily.
Here is a PR https://github.com/ethereum/browser-solidity/pull/802

**Comment by serapath** [comment]
copied all stuff from the above code snippet to the PR and tried to include your feedback. let's continue there

**Comment by serapath** [comment]
https://github.com/ethereum/browser-solidity/pull/802
