### ISSUE TITLE
Metamask: Injected Web3 is not working

### ISSUE THREAD

**Issue by anuragverma639** [ethereum/browser-solidity#491]
I am using Metamask for ethereum testnet. And when i deploy my contract it run in my memory. And when I select the Injected Web3. It is not selected. Now what to do??
![untitled](https://cloud.githubusercontent.com/assets/26744696/24413178/4a85b666-13f8-11e7-8e0f-6e6a623f9ec9.png)
.

**Comment by chriseth** [comment]
Do you have any errors in the browser error console?

**Comment by anuragverma639** [comment]
No it is not showing any error.When i click the create button contract is not mined using metamask because JavascriptVM is selected. But when I select injected web3 it did not selected.

**Comment by johnfkneafsey** [comment]
Having the exact same issue here while trying to deploy the Congress contract from the tutorial.

**Comment by flyswatter** [comment]
Sorry, this is because metamask introduced a requirement for a `<!doctype html>` header, but this app does not have one.

We're rolling that requirement back in metamask, should be fixed in an hour, although browser-solidity should also add the header.

**Comment by kumavis** [comment]
Fixed by https://github.com/ethereum/browser-solidity/pull/492

**Comment by kumavis** [comment]
This issue was also resolved in upstream metamask. It can be closed now.

**Comment by anuragverma639** [comment]
Issue is resolved. Metamask is updated.
