### ISSUE TITLE
Contract tab

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/browser-solidity#510]
## Above the contract
- [x] add loading (spinner) and move to become first and default tab (https://github.com/ethereum/browser-solidity/pull/532)
- [x] move environment dropdown on top (old-needs to be closed: https://github.com/ethereum/browser-solidity/pull/530)(new: https://github.com/ethereum/browser-solidity/pull/533)
- [x] see if we can make transaction origin content copyable
- [x] fix positioning of dropdown menues and titles (one next to another or one below another)(https://github.com/ethereum/browser-solidity/pull/533)
- [x] see what to do with value tip (e.g. .7 ether or 5 wei, defaults to ether) (https://github.com/ethereum/browser-solidity/pull/533)

## Contract
https://imagebin.ca/v/3IiCPlsEPRYK
- [x] title to the contract instance header (maybe different color to differentiate contract 'template/class' from contract instance) (https://github.com/ethereum/browser-solidity/pull/533)
- [x] right below contract instance put address (at) (copy to clipboard?) (https://github.com/ethereum/browser-solidity/pull/533)
- [x] move all details about the contract under new button Contract bytecode, Interface... https://github.com/ethereum/browser-solidity/pull/533

**Comment by chriseth** [comment]
About copying transaction origin: I guess the easiest solution for now would be to have a button "copy current address to clipboard" and use the browser functionalities.

About the contract instance header: It should already have a different title.

I also changed all items to checkboxes, so the progress is better visible. Please try to submit a single pull request per item.

**Comment by yann300** [comment]
you could take a look at https://www.npmjs.com/package/copy-to-clipboard for the copy to clipboard

**Comment by ninabreznik** [comment]
Thanks @chriseth && @yann300

**Comment by yann300** [comment]
@ninabreznik is https://github.com/ethereum/browser-solidity/issues/501 going to be done in this issue?
would be good to normalize the padding.
