### ISSUE TITLE
Decoding events from libraries

### ISSUE THREAD

**Issue by Zvezdin** [ethereum/browser-solidity#518]
Hello. Remix is not able to decode events fired from libraries. See the following source code: https://pastebin.com/mNnYqPjS
Event "ReplaceEvent" in the library is not decoded properly, while "EventReplace" in the contract is. The web browser console prints "cannot find event for log" when the transaction is complete.

Is this a solidity issue, or a remix one? Can I receive events from libraries?

**Comment by yann300** [comment]
that's a remix issue

**Comment by yann300** [comment]
fixed
