### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/browser-solidity#53]
When you close a file tab, the above JavaScript error occurs. I'm seeing this on Mac OS X 10.10.5, with Chrome 50.0.2661.102 (64-bit).

**Comment by Denton-L** [comment]
It appears that `editor.getSession()` and `editor.on()` are both not defined, even though it's been used it earlier code.

**Comment by chriseth** [comment]
Is this fixed?

**Comment by Denton-L** [comment]
Yes, should be fixed now.
