### ISSUE TITLE
Display console

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#535]
Use this console to log transactions (containing contractname, address, function name, transaction cost) and an action to start debugging.

**Comment by ninabreznik** [comment]
Example 
https://codepen.io/anon/pen/XgjEae?editors=0010

Sourcecode
https://github.com/serapath/dom-console/blob/master/domconsole.js

**Comment by yann300** [comment]
- filtering
- manually input js code in the console and eval it against the current web3

**Comment by serapath** [comment]
* add message logging
  * `transactionExecuted` + information about it
  * anything that happens in the background related to an address we know
* add maybe `debug button` next to logged messages
* add javascript command line

**Comment by yann300** [comment]
- if `console.log` in the general context (remix code for instance), it should not log to the domconsole.
 - if a script that uses `console.log` is executed in the console, it should log to the dom-console.
 - the state of variables declared in the dom-console should be persistent.
 input => ´var test = 45´
 then => `test` should log 45
