### ISSUE TITLE
Transaction gas limit & Value are not accessible from firefox

### ISSUE THREAD

**Issue by mhgharieb** [ethereum/browser-solidity#546]
On Online IDE, 
the fields, Transaction gas limit & Value, are not accessible nor editable from Firefox 53.0.2 (64-bit)

**Comment by Metaception** [comment]
Can confirm...these fields used to work in old releases (Before the GUI redesign)

**Comment by D-Nice** [comment]
To confirm, I'm having similar issues with an older Chromium-based browser. For me the `transaction gas limit` box appeared disabled. Opening the browser's developer's tools and clearing `col2_2AcnlV display-box-L_45hQ0T` from the box's class attribute rectified the issue, but it's a hacky band-aid.
