### ISSUE TITLE
Restrict editor size while resizing

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#549]
If the area for the editor is already quite small and the browser window width is decreased, it can happen that the editor receives a zero width or even negative width with the effect that it is not even possible to resize the right hand panel anymore. With every change to the layout, we should force a certain minimum size of the editor. This should also work if I open remix with empty localstorage in a small browser window.

**Comment by ninabreznik** [comment]
Already included in https://github.com/ethereum/browser-solidity/pull/649
