### ISSUE TITLE
highlighting tab title when the content of the tab display a warning

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/browser-solidity#566]
![remix](https://cloud.githubusercontent.com/assets/1076427/26589253/d62b4b96-4557-11e7-8481-b84c84f2e300.png)

![screen shot 2017-05-30 at 4 48 01 pm](https://cloud.githubusercontent.com/assets/1076427/26589265/ddd42610-4557-11e7-9528-f95b629042f6.png)

**Comment by yann300** [comment]
that is already working, just need refactoring

**Comment by ninabreznik** [comment]
@yann300 Created a PR for this https://github.com/ethereum/browser-solidity/pull/587
