### ISSUE TITLE
Error with payable contracts

### ISSUE THREAD

**Issue by Zvezdin** [ethereum/browser-solidity#568]
Hello. I've got the following contract in browser solidity: https://pastebin.com/WVWj6g6E
It's a dummy payable contract without many security measures.

However, it can't even be published from browser solidity. I get an error that "callback contain no result Gas required exceeds limit: 4951875". 

If I simply copy the contract publish JS code (provided in browser solidity) and run it in my browser's console, all works well.

Same problem with calling any contract methods (except for the getBalance method). Can't run from browser solidity, executes perfectly fine when called from web3.

Ps: I'm using Metamask (working and properly configured) as a web3 provider in browser solidity.

What is this issue about?

**Comment by yann300** [comment]
fix https://github.com/ethereum/browser-solidity/pull/570

**Comment by yann300** [comment]
should be fixed now. please reopen if not
