### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by ethers** [ethereum/browser-solidity#57]
Related to tests, some kind of CI would be helpful.

Seems it's down currently, due to:
app.js:99078 Uncaught TypeError: Cannot read property 'eth' of undefined
This one has been reported: https://github.com/ethereum/browser-solidity/pull/50#issuecomment-223776311

**Comment by axic** [comment]
Fixed in #56

**Comment by axic** [comment]
We badly need unit and integration tests. I think it will come along soon given the ongoing efforts of cleaning up the code base.

**Comment by redsquirrel** [comment]
Challenge accepted 🚑

**Comment by axic** [comment]
Maybe track this in #8?
