### ISSUE TITLE
Navigation bar rendering issue on a certain reolution

### ISSUE THREAD

**Issue by Zvezdin** [ethereum/browser-solidity#574]
Hello. On the resolution of 1920x1080, the following can be observed on the navigation bar of open files: http://i.imgur.com/8kSLcWy.png

This can be fixed with zooming in / out. 

Also, is there a way to change the font size of the code? It is unnecessarily huge on some devices.

**Comment by ninabreznik** [comment]
Most probably fixed with https://github.com/ethereum/browser-solidity/pull/649

Can you please check it out @Zvezdin ?
