### ISSUE TITLE
Incorrect Indexed Event Parameter Value Displayed

### ISSUE THREAD

**Issue by kieranelby** [ethereum/browser-solidity#575]
If I create this contract at https://ethereum.github.io/browser-solidity/ using the Javascript VM execution environment:

```
pragma solidity ^0.4.11;
contract Foo {
   
    event ExampleEvent (
        uint indexed a,
        uint b
    );
    
    function generateExampleEvent() {
        ExampleEvent(123, 456);
    }
    
}
```

Then when I execute the generateExampleEvent function by clicking the button, I see my event appear in the "Events" section of the UI - but with the value zero instead of the expected 123 for one of the parameters:

```
ExampleEvent[
  "456",
  "0"
]
```

If I remove the "indexed" from the event parameter, I see the correct value (but there's no indication of which parameter is which - they seem to appear in reverse order with no names).

Afraid I haven't tried with other execution environments - but at least it's a nice easy test case ...

**Comment by Janaka-Steph** [comment]
Same here, indexed event doesn't work using Javascript VM but works on Kovan.

**Comment by yann300** [comment]
should be fixed by the new interface
