### ISSUE TITLE
Editor window - font-size vmin - it's a terrible experience...

### ISSUE THREAD

**Issue by stefek99** [ethereum/browser-solidity#576]
I see some CSS classes related to `ACE` editor...

On my machine font-size is bound to height of the window, I cannot simply `ctrl +` to see more code on the screen, it's a terrible experience, limiting to only 36 lines of code...

**Comment by ninabreznik** [comment]
Thanks @stefek99 
@yann300 I prepared a PR for this https://github.com/ethereum/browser-solidity/pull/577

**Comment by stefek99** [comment]
**WAT**

Did you manage to respond to my issue and provide PR in 20 minutes?

**Comment by ninabreznik** [comment]
Lol, @stefek99 that was a coincidence :) But yes, I am also proud of that :)

**Comment by yann300** [comment]
should be better now, please reopen if not
