### ISSUE TITLE
How to compile a contract to the bytecode?

### ISSUE THREAD

**Issue by stefek99** [ethereum/browser-solidity#578]
I'm experimenting with: https://www.ethereum.org/token

Initially I used default Ethereum client, as suggested in the article.

Here is my code: https://gist.github.com/stefek99/e73e3b6a381ac08bd1fe3f47e8d175a5

_(just hardcoded some values)_

Contract creation: https://etherscan.io/address/0x3c27a55b7fffa58cde786db5659a67b67ddd098b#code

Token: https://etherscan.io/token/0x3c27a55b7fffa58cde786db5659a67b67ddd098b

The issue I'm having is that I cannot verify the contract, I informed Etherscan guys: https://twitter.com/stefek99/status/871175876779675648

Instead I'm trying to follow strategy here: https://ethereum.stackexchange.com/a/3257/2524

> If getting verified on EtherScan is important to you, then write your Solidity code where ever but compile it using Browser Solidity here: http://chriseth.github.io/browser-solidity/

> Then use that bytecode to deploy. I have not tested it but the code it spits out for the sample token contract matches what EtherScan spits out. I assume that EtherScan is using that same browser based compiler to check and verify contracts.

### Here is the error I'm getting:

<img width="1611" alt="remix_-_solidity_ide" src="https://cloud.githubusercontent.com/assets/249703/26758158/f27cae60-48cd-11e7-9e5a-14d5112c54cb.png">

So in a way I've asked a convoluted question - https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem 

But maybe you'll know - how to compile it to the bytecode?

**Comment by yann300** [comment]
you have this error because no `transaction origin` has been selected. 
you are using the `injected provider`. (Metamask or Mist)?

**Comment by stefek99** [comment]
Metamask installed as Chrome extension, running in the background.

Mist install on my computer, at the time of taking screenshot not running.

Will try again with selected `transaction origin`.

**Comment by yann300** [comment]
i close. please  reopen if necessary
