### ISSUE TITLE
"At Address" not working + create shows Error - callback contain no result Error: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#586]
i am trying build a contract on rinkeby network through metamask but when i click create it shows error - callback contain no result Error: SyntaxError: Unexpected token < in JSON at position 0
prior to create there is no error in the contract and is build with no errors .
"At Address" button is also not working on clicking it shows pop up that enter the address but after entering and clicking it is not doing anything.
i am in middle of something very important please help ? Thanks.

Original issue (including screenshot): https://github.com/ethereum/solidity/issues/2352

**Comment by yann300** [comment]
@vanshaj2608 could you retry the atAddress now?

**Comment by qjflores** [comment]
this looks like this is working now

**Comment by yann300** [comment]
and the creation too?

**Comment by yann300** [comment]
i close please reopen if necessary
