### ISSUE TITLE
Add "publish" button for publishing to the blockchain.

### ISSUE THREAD

**Issue by flyswatter** [ethereum/browser-solidity#59]
*When* browsers who have `web3` available visit your page, it would make sense to provide a `Publish` button that allows publishing the compiled bytecode to the blockchain.

If you need a web3 browser to practice with, I would welcome you to join the MetaMask private beta.

**Comment by redsquirrel** [comment]
@flyswatter browser-solidity already has some functionality that's very close to this. First, every contract has a "Create" button, which publishes it to the current execution context. By default, the execution context is set to an in-memory VM, but it can also be toggled to a specific Web3 Provider Endpoint.

![solidity_realtime_compiler_and_runtime](https://cloud.githubusercontent.com/assets/2512/15805161/eb445db0-2ae6-11e6-98dc-f51db3196c99.png)

If someone has a browser extension that provides a `web3` object to the page, it sounds like you're asking for browser-solidity to provide an additional option to use that object as the execution context?

**Comment by flyswatter** [comment]
That's exactly right! If an existing web3 is detected, ideally a call is made to web3.version.getNetwork(callback(error, result){ ... }) to identify whether this is the main net, test net, or an unknown network, and then adding an option like "web3 browser detected on Morten test network. Deploy with it."

Really if you detect a web3 object you could probably skip showing the http provider UI, it would be redundant.

- Dan

**Comment by redsquirrel** [comment]
OK, yeah, can I get that invite to the web3 browser so I can see how it exposes web3?

**Comment by flyswatter** [comment]
Sent via direct slack message

**Comment by redsquirrel** [comment]
Looking at the codebase again, it appears that at least from a web3 object perspective, browser-solidity already supports MetaMask via its [solidity-adapter](https://github.com/ethereum/browser-solidity/blob/master/src/web3-adapter.js). I'm doing some further testing.

**Comment by redsquirrel** [comment]
In order to actually use the web3 object supplied by Mist or MetaMask, we need to rework the `executionContext` setup and selection.

**Comment by redsquirrel** [comment]
This will be supported if #62 is merged.

**Comment by flyswatter** [comment]
Great work, Dave!

- Dan
