### ISSUE TITLE
for loop takes forever with condition more than 0xFF

### ISSUE THREAD

**Issue by iFA88** [ethereum/browser-solidity#590]
Greetings.
I have discovered a bug for `FOR` loop. This is maybe a solidity bug.
The `FOR` condition uses only 1 byte number. If I give number `256` or `uint256(256)` then the loop will take forvere.
Example:
```javascript
contract tester {
    bool varka;
    function test() {
        for ( var r=0 ; r < 255 ; r++ ) {
            varka = true;
        }
    }
}
```
This works fine.
When I test this:
```javascript
contract tester {
    bool varka;
    function test() {
        for ( var r=0 ; r < uint256(256) ; r++ ) {
            varka = true;
        }
    }
}
```
This takes forever.

I use:
https://ethereum.github.io
JS VM
0.4.11+commit.68ef5810.Emscripten.clang
Optimization is true
Firefox 53.0.3. 64bit

**Comment by iFA88** [comment]
if i use this, then works:
```javascript
contract tester {
    bool varka;
    function test() {
        for ( uint256 r=0 ; r < 256 ; r++ ) {
            varka = true;
        }
    }
}
```

**Comment by iFA88** [comment]
Its really confusing, when I debug the transaction what gives out of gas, in the last step the `r` value has much more than 0xFF .

**Comment by chriseth** [comment]
This is a known pitfall:

 - https://solidity.readthedocs.io/en/develop/security-considerations.html#minor-details 
 - https://ethereum.stackexchange.com/questions/305/what-are-common-pitfalls-or-limitations-when-coding-in-solidity

We should probably create a warning for that: https://github.com/ethereum/solidity/issues/2358
