### ISSUE TITLE
testrpc interface panel

### ISSUE THREAD

**Issue by skilesare** [ethereum/browser-solidity#597]
It would be great to have a panel on the contract page where we could send testrpc messages to blockchain environment.  This is specifically useful in testing when you need to simulate the passage of time.

```
   web3.currentProvider.sendAsync({
            jsonrpc: "2.0",
            method: "evm_increaseTime",
            params: [86400 * 34],
            id: new Date().getTime()
          }
```

There may be a better handle for doing this, but when I try to inspect source and call this it gets ahold of the metamask instance and not my local rpc instance that I'm running.

Looks like the web3 is in the ExecutionContext.  I couldn't quickly find a handle on that object.

**Comment by yann300** [comment]
yes that's planned soon

**Comment by yann300** [comment]
will be addressed by https://github.com/ethereum/browser-solidity/issues/535

**Comment by yann300** [comment]
now that you can use web3 in the terminal that should be doable.
