### ISSUE TITLE
Current "Best Practice" for writing JavaScript Modules

### ISSUE THREAD

**Issue by serapath** [ethereum/browser-solidity#605]
# Current "Best Practice" Conventions
* look them up
* discuss them
* update them

## Module Definition (example)
```js
// user-card.js
var yo = require('yo-yo')
var csjs = require('csjs-inject')
var EventManager = require('ethereum-remix').lib.EventManager

var css = csjs`
  .userCard        {
    position       : relative;
    box-sizing     : border-box;
    display        : flex;
    flex-direction : column;
    align-items    : center;
    border         : 1px solid black;
    width          : 400px;
    padding        : 50px;  
  }
  .clearFunds { background-color: lightblue; }
`

class UserCard {
  constructor (opts = {}) {
    var self = this

    self.event = new EventManager()
    self._api = opts.api
    self._view = undefined
    self.data = {
      title: opts.title,
      name: opts.name,
      surname: opts.surname,
      totalSpend: 0,
      _nickname: opts.nickname,
      _funds: self._appAPI.getUserFunds()
    }
    var events = opts.events

    events.funds.register('fundsChanged', function (amount) {
      if (amount < self.data._funds) self.data.totalSpend += self.data._funds - amount
      self.data._funds = amount
      self.render()
    })
  }
  render () {
    var self = this
    var el = yo`
      <div class=${css.userCard}>
        <h1> @${self.data._nickname} </h1>
        <h2> Welcome, ${self.data.title || ''} ${self.data.name || 'anonymous'} ${self.data.surname} </h2>
        <ul> <li> User Funds: $${self.data._funds} </li> </ul>
        <ul> <li> Spent Funds: $${self.data.totalSpend} </li> </ul>
        <button class=${css.clearFunds} onclick=${e=>self._spendAll.call(self, e)}> spend all funds </button>
      </div>
    `
    if (self._view) yo.update(self._view, el)
    else self._view = el
    return self._view
  }
  update (data = {}) {
    var self = this
    if (!self._view) self._constraint('first initialize view by calling `.render()`')
    if (data.hasOwnProperty('title')) self.data.title = data.title
    if (data.hasOwnProperty('name')) self.data.name = data.name
    if (data.hasOwnProperty('surname')) self.data.surname = data.surname
    self.render()
  }
  getNickname () {
    var self = this
    return `@${self.data._nickname}`
  }
  getFullName () {
    var self = this
    return `${self.data.title} ${self.data.name} ${self.data.surname}`
  }
  _spendAll (event) {
    var self = this
    self._appAPI.clearUserFunds()
  }
  _constraint (msg) { throw new Error(msg) }
}

module.exports = UserCard
```
## Module Usage (example)
```js
/*****************************************************************************/
// 1. SETUP CONTEXT
var EventManager = require('ethereum-remix').lib.EventManager
var funds = { event: new EventManager() }
var userfunds = 15
function getUserFunds () { return userfunds }
function clearUserFunds () {
  var spent = userfunds
  userfunds = 0
  console.log(`all funds of ${usercard.getFullName()} were spent.`)
  funds.event.trigger('fundsChanged', [userfunds])
  return spent
}
setInterval(function () {
  userfunds++
  funds.event.trigger('fundsChanged', [userfunds])
}, 100)

/*****************************************************************************/
// 2. EXAMPLE USAGE
var UserCard = require('./user-card')

var usercard = new UserCard({
  api: { getUserFunds, clearUserFunds },
  events: { funds: funds.event },
  title: 'Dr.',
  name: 'John',
  surname: 'Doe',
  nickname: 'johndoe99'
})

var el = usercard.render()
document.body.appendChild(el)
setTimeout(function () { usercard.update({ title: 'Prof.' }) }, 5000)
```

**Comment by yann300** [comment]
yo example : https://github.com/ethereum/remix/blob/master/src/ui/BasicPanel.js

**Comment by yann300** [comment]
In the above file (BasicPanel):
 - calling `render`returns the DOM element processed by yoyo. the BasicPanel instance keep a ref of the DOM element.
 - when the `update` function is called. yo update the DOM: `yo.update(this.view, this.render())` .
 - it is still possible to use document.querySelector('...') to update the DOM without yoyo

**Comment by yann300** [comment]
That would be better to use es6 class than prototype...
For the public / private properties issue, we could do:
```
class person {
    constructor(name) {
        var _name = name
        this.setName = function(name) { _name = name; }
        this.getName = function() { return _name; }
    }
}
```
or even, yes using just underscore to mark property that should not be changed.....
```
class person {
    constructor(name) {
        this._name = name
    }
}
```

**Comment by serapath** [comment]
Just for some background:
When working with unknown code, fastest and most convenient (=takes less discipline) for me is to `console.log(obj)` and see what methods/properties it has - so i prefer "internals" to be hidden over extra work and discipline to keep extra documentation up2date and always to remember to look it up.

So **+1** for:
```js
class person {
    constructor(name) {
        var _name = name
        this.setName = function(name) { _name = name; }
        this.getName = function() { return _name; }
    }
}
```


> In the above file (BasicPanel):
> - calling `render`returns the DOM element processed by yoyo. the BasicPanel instance keep a ref of the DOM element.
> - when the `update` function is called. yo update the DOM: `yo.update(this.view, this.render())` .
> - it is still possible to use document.querySelector('...') to update the DOM without yoyo

I agree.
One question regarding: https://github.com/ethereum/remix/blob/master/src/ui/BasicPanel.js
In this example - by convention (we should document that):
* developers are not supposed to ever call `.render()` again, right?
* developers should not overwrite `this.view` manually, but probably `this.data` should be set by them
* `this.width` and `this.height` can be set, but for show/hide, we use methods instead of e.g. `this.display`

**Comment by yann300** [comment]
sorry, scratch what I said for private properties.

```
/********** PRIVATE **********/
    var appEvents = opts.appEvents
    var appAPI = opts.appAPI
    var nickname = opts.nickname
    var funds = appAPI.getUserFunds()
    var view
    /********** PRIVATE helpers (need access to private date) **********/
    function update () {
      if (!view) constraint('first initialize view by calling `.render()`')
      self.render()
    }
```

I don't think it is a good way to go. let's discuss that soon

**Comment by serapath** [comment]
@ninabreznik @yann300 @chriseth @ryestew
I changed all that was private into public properties where names start with `_` to indicate they are meant to be private.

Feedback welcome

**Comment by ninabreznik** [comment]
I unfortunately can't give a comment o the details, because I don't follow the standards so closely and can't see what's now the best thing. I know that @serapath is watching closely at what JS community (specially hyper-modular crew)is saying about different best practices, so I trust that he will find the best way to make things minimal, simple and up to date :)

PS: Checked the example and it looks fine to me. I personally don't use ES6, only maybe for arrow functions (`=>`) etc.
