### ISSUE TITLE
Execute contract from browser

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/browser-solidity#610]
Everytime change contract we need to past it to web3 command and miner.start then execute contract function.

Are there some tool that like Remix but can execute function directly in web UI?

https://github.com/ethereum/solidity/issues/2477#issuecomment-311957082

**Comment by yann300** [comment]
You mean that if the contract code change, it will be automatically deployed and your node will also start to mine ?

cause  you say:
"Are there some tool that like Remix but can execute function directly in web UI?"
you can already execute solidity function from the web UI using Remix... the thing is that if you use an external private / dev node, you will need to manually start debugging. (is that your issue ?)

**Comment by EasonWang01** [comment]
Yes,kind of.

>you can already execute solidity function from the web UI using Remix.
Where can we execute solidity function from the web UI?Because I not saw kind of things in WEB UI.

thanks

**Comment by yann300** [comment]
browse remix.ethereum.org, you will see by default the `ballot` contract, click on the `Create` button on the rigth panel, that will deploy an instance of `Ballot`, then you can click on the corresponding functions of `Ballot`.
I close this for now, please go to https://gitter.im/ethereum/remix for any question.

**Comment by EasonWang01** [comment]
Still not saw the Create button,can you point me out,thanks

![asdasdasd](https://user-images.githubusercontent.com/11001914/27785998-0b5c4908-6012-11e7-9944-b9a8bd52069b.png)

**Comment by yann300** [comment]
red button (bottom right)

**Comment by EasonWang01** [comment]
no red button,can you give me a screen shot?
