### ISSUE TITLE
accounts not showing

### ISSUE THREAD

**Issue by btcunbranded** [ethereum/browser-solidity#611]
when accessing 
https://remix.ethereum.org/#version=soljson-v0.4.11+commit.68ef5810.js
inject web3 auto selected but no accounts available, it is blank.
accounts show if select javascript vm
please advise
thankyou roy

**Comment by yann300** [comment]
Which provider are you using ? (mist or metamask ?)?. 
In mist you first have to allow the dapp to use your accounts (Connect button)

**Comment by yann300** [comment]
I close please reopen if you still encounter this error
