### ISSUE TITLE
CORS problem connecting remix to localhost geth.exe

### ISSUE THREAD

**Issue by stiv-yakovenko** [ethereum/browser-solidity#620]
HI! Can't connecte remix, though I try to follow various instructions from the net, hopefully screenshot contains all info you might need to give me advice: 

<img width="797" alt="remix2" src="https://user-images.githubusercontent.com/4163254/28094827-3e868948-66c9-11e7-9f4a-d1e8970ed045.png">

Thanx in advance.

**Comment by chriseth** [comment]
You need to load the website using `http` instead of `https`. Otherwise, the browser refuses to connect to geth over a non-ssl connection.

**Comment by stiv-yakovenko** [comment]
no, this doesn't help

<img width="816" alt="gethshit" src="https://user-images.githubusercontent.com/4163254/28112333-ddd0d162-6722-11e7-94ff-2ccdb1986ff4.png">

**Comment by chriseth** [comment]
I think if you use `attach` in the commandline, it just attaches to another geth process that is already running, so it does not really change the RPC parameters. Can you try running just `geth --rpc --rpccorsdomain '*'`?

**Comment by stiv-yakovenko** [comment]
@chriseth , the problem resolved, i am passing parameters to mist.exe this way:
"C:\Program Files\mist\win-unpacked\Mist.exe" --node-rpccorsdomain "*" --node-rpcport "8545" --node-rpc

Thank you so much

**Comment by chriseth** [comment]
Oh, you are using mist? Then you can also start remix from inside mist, by the way.

**Comment by markshw** [comment]
Hi @chriseth, @stiv-yakovenko 
Are you able to see the source code and variables with geth and remix?
thanks a lot
