### ISSUE TITLE
Publish to Gist button does not work

### ISSUE THREAD

**Issue by bbuenz** [ethereum/browser-solidity#622]
I am using the version at https://remix.ethereum.org/ but the Gist button does not work anymore.

**Comment by yann300** [comment]
will fix that. note that you can now use remix with local files: 
https://remix.readthedocs.io/en/latest/tutorial_remixd_filesystem.html

**Comment by bbuenz** [comment]
Thanks is there a way to move the files from the online storage to local storage other than copy pasting out of the gui?
