### ISSUE TITLE
JavascriptVM account balance reduced by much more than the contract deployment cost

### ISSUE THREAD

**Issue by davebryson** [ethereum/browser-solidity#636]
When using the JavascriptVM environment, the pre-populated account balance of the deploying address is greatly reduced by much more than the actual contract deployment cost.  In fact, it appears that regardless of the contract cost, the account is always reduced to: `0.000000000005525819 ether`

This is using the latest online version or browser-solidity

**Comment by yann300** [comment]
thanks for the report, will fix asap 
duplicates https://github.com/ethereum/remix/issues/528

**Comment by yann300** [comment]
https://github.com/ethereum/browser-solidity/pull/639
