### ISSUE TITLE
Group storage related methods

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#64]
Currently the storage related methods are scattered through different files:
- [x] rename `storage-handler.js` to `storage.js`
- [x] move file loading into it
- [ ] move caching into it
- [x] create a global instance (needed for effective caching) and use it in all sources
- [x] alternatively create the storage instance on the top level and pass it down to every module

**Comment by chriseth** [comment]
In addition to that, we should also encapsulate the file-handling and separate it from the generic "persistency" provider.

**Comment by redsquirrel** [comment]
@axic Can you review #72 (just merged) and see where this issue stands?

**Comment by axic** [comment]
@redsquirrel I see that caching is part of the `editor` instance? Is that correct?

**Comment by redsquirrel** [comment]
@axic What kind of caching are you looking for?

**Comment by chriseth** [comment]
@axic can you elaborate on the caching part here, please, so we can close this issue?

**Comment by axic** [comment]
We have a couple of random things name *cached*:
- `getEditorSize` / `setEditorSize` in app.js + app/storage.js
- `utils.isCachedFile`

I think storage.js:
- shouldn't contain these `EditorSize` methods
- should use a proven localStorage abstraction (e.g https://www.npmjs.com/package/store)

**Comment by chriseth** [comment]
Ah yes, the "cached" part of some variable names should go completely, there is nothing "cached" about it.

**Comment by axic** [comment]
I think editor should have the following:
- createEmptyFile(name)
- getFileContent(name)
- setFileContent(name, content)
- hasFile(name)
- renameFile(oldName, newName)
- switchToFile(name)
- getFileList() -> array of file names

**Comment by chriseth** [comment]
I agree with the methods, but why should they be part of the editor? I think all of them except `switchToFile` should be methods of the storage abstraction, where the editor registers for change events (`fileChanged`, `fileRenamed`, `fileCreated`, `fileDeleted`).

Furthermore, please already keep in mind that `name` will be a path in the future, but I think we can still keep it a simple string with `/` as directory separator.

**Comment by chriseth** [comment]
If this is just meant as a first step into that direction, then "big thumbs up" :-)

**Comment by axic** [comment]
I'm currently inclined to look at "editor" as the abstraction maintaining the files available, including the one currently being changed.

It may be better to actually have 3 different modules:
- "files"
- editor
- storage

Basically I would like to simplify how `app.js` handles files.

**Comment by chriseth** [comment]
My suggestion would be:
- editor: ACE plus tabs / tree view of files
- "files": interface creating a tree view of files over localStorage, perhaps also allowing for remote files
- storage: thin layer above localStorage

Correct me if I am wrong, but I think that an ACE session basically corresponds to an "open" files (even if it is not displayed) storing things like cursor position and so on. The tabs are not part of ACE, the editor creates them itself.

**Comment by axic** [comment]
> storage: thin layer above localStorage

I am actually not very convinced we need it and would prefer to use *store* (https://www.npmjs.com/package/store) as the `localStorage` wrapper.

> Correct me if I am wrong, but I think that an ACE session basically corresponds to an "open" files 
> The tabs are not part of ACE, the editor creates them itself.

That's correct as far as I understand it right now.

**Comment by chriseth** [comment]
I don't see what "store" provides over what we currently have. The thin layer I was talking about is required because we do not only store files in localStorage, we also store settings.

**Comment by axic** [comment]
Replaced by #384.
