### ISSUE TITLE
Relative imports do not work in the browser namespace

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#642]
Inside `browser/a.sol`, an import `import "./x.sol";` does not find `x.sol`, although `browser/x.sol` works.
It seems like `a.sol` is not properly passed to the compiler with its fully qualified name, or there are some problems with slashes in the beginning.

**Comment by yann300** [comment]
I can't reproduce - both `import "./Untitled1.sol"; ` and import `"browser/Untitled1.sol";` work . Are you sure it was with the `browser` namespace ?

**Comment by chriseth** [comment]
I still have it here...

**Comment by asifmallik** [comment]
This is still happening to me.
