### ISSUE TITLE
Terminal Stuff

### ISSUE THREAD

**Issue by serapath** [ethereum/browser-solidity#657]
- ~~[ ] we should use the same rendering as for the chrome devtool console~~
- ~~[ ] the horizontal drag bar is too large (that because of the collapse button). an idea: setting the bar height as minimun as possible and put the collapse button in the upper-right corner of the console.~~
- ~~[ ] when resizing, the drag bar takes the entire browser width...~~
- [x] keep history of execution, arrow up/down should propose last executed script
- [x] clear the logs
- [x] filter (any content).
- [x] grouping or "follow a series of related log entries" (e.g. all logging caused by a specific pasted script)

**Comment by serapath** [comment]
@ninabreznik 
I think next to the re-styling of the terminal, there needs to be a "ui concept & design" for the terminal bar to contain:
* a `clear logs` button
* a `select dropdown` to select either `"JS"` or `"Transaction"`
* an `filter input field` to show only selected messages that contain/match what the user writes
* (maybe a way to have multiple terminal TABs)

**Comment by yann300** [comment]
done
