### ISSUE TITLE
UX - Terminal 

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/browser-solidity#675]
#657

**Comment by ninabreznik** [comment]
Some ideas/solutions

![screen shot 2017-08-19 at 12 59 06 am](https://user-images.githubusercontent.com/1076427/29481513-d584dd7c-8479-11e7-8970-ab8113d5f7a6.png)
![screen shot 2017-08-19 at 12 58 28 am](https://user-images.githubusercontent.com/1076427/29481512-d57fcc88-8479-11e7-966e-cab3678188bd.png)

**Comment by yann300** [comment]
**log unknown transaction:**

`block:806226, txIndex:0: from:0xdf0...7f6fe, to:0x2a6...11fe2, value:0 wei, data:0xa90...54000, hash:0x911...7707d, <ACTION_DEBUG>`

Details should maybe show something similar as the contract details modal dialog (e.g a way to easily copy `from`, `to`, `value`, `data`, `log data` etc...), let's limit to that field for now.

**log known transaction:**

ex for contract creation:
`block:806255, txIndex:0: from:0x4e7...602f1, to:, browser/Untitled:T2.(constructor), value:0 wei, data:0x606...80029, 0 logs, hash:0x258...36621,`

ex for function call:
`block:806271, txIndex:0: from:0x4e7...602f1, to:0xe64...73a36, browser/Untitled:T2.test(), value:0 wei, data:0xf8a...8fd6d, 1 logs, hash:0x1b6...aba32,`

Details should show the same stuff as unknown transaction and: contract name, function name, decoded logs, decoded input param.

if remix is using the javascript VM, we would display the same thing as *log known transaction* but without block and txIndex. like:
`(vm): from:0xca3...a733c, to:, browser/Untitled:T2.(constructor), value:0 wei, data:0x606...80029, 0 logs, hash:0xd64...08529,`
`(vm): from:0xca3...a733c, to:0x692...77b3a, browser/Untitled:T2.test(), value:0 wei, data:0xf8a...8fd6d, 1 logs, hash:0x1b7...e2620,`
And we can display decoded out param in the details.

In the code, this function returns a known transaction dom element:
https://github.com/ethereum/browser-solidity/blob/master/src/app/execution/txLogger.js#L45

this function returns an unknown transaction dom element:
https://github.com/ethereum/browser-solidity/blob/master/src/app/execution/txLogger.js#L57

**Comment by ninabreznik** [comment]
Here's first draft. I went with showing details inside of the terminal. Somehow it feels better and intuitive. I kind of feel that when you are in terminal, popups don't feel right, so maybe we could display stuff rather inside of the terminal in this case.
https://github.com/ethereum/browser-solidity/pull/755

**Comment by yann300** [comment]
right displaying everything in the terminal feel nicer

**Comment by ninabreznik** [comment]
[This PR](https://github.com/ethereum/browser-solidity/pull/755) i updated. What's missing:

* copy to clipboard (after the key like in Modal dialog or after the value (like in RUN tab)? )
* margin/padding for VM logs (they are more apart than other tx logs)

Regarding TERMINAL in general:
- more margin in left and right side (see how it looks if both left and right panels are collapsed)
- notification about new entries should be smaller (maybe same size as tittles on the editor tabs - these are currently the biggest and boldest fonts we have)
![screen shot 2017-09-03 at 5 52 57 pm](https://user-images.githubusercontent.com/1076427/30004995-e1e6cab8-90d0-11e7-82e0-6a56ca4d008d.png)

**Comment by ninabreznik** [comment]
TODOS left:
* copy data from table
* to: without, 0 logs, just the contract name + * function (if (resovedData) display contractname.function name in the log)
* logs in the table: 0 or logs
* if (resolvedData) then in details/table

**Comment by yann300** [comment]
done
