### ISSUE TITLE
Send 1000s of request/second to the ethereum node

### ISSUE THREAD

**Issue by asimashfaq** [ethereum/browser-solidity#681]
When i connect remix to my ethereum node it start sending  1000s request/s to the server which result in crash

**Comment by yann300** [comment]
1000 /s ? it call eth_getBalance and eth_getBlockByNumber yes but not at this rate.
Do you have a lot of managed account in your local node?
could you send the called rpc endpoints ?

**Comment by yann300** [comment]
that should not happen. please reopen if needed
