### ISSUE TITLE
Cannot read property 'relevantNodes' of undefined

### ISSUE THREAD

**Issue by PatchRanger** [ethereum/browser-solidity#702]
### Problem
Using http://ethereum.github.io/browser-solidity/#version=soljson-v0.4.15+commit.bbb8e64f.js I've connected to my own Ethereum node remotely by RPC.
It looks well - I see successful requests in Network tab of my browser.
The problem is this console message - I guess, something goes wrong:
```js
Uncaught TypeError: Cannot read property 'relevantNodes' of undefined
    at constantFunctions.visit (http://ethereum.github.io/browser-solidity/build/app.js:133722:89)
    at http://ethereum.github.io/browser-solidity/build/app.js:135298:22
    at Array.map (native)
    at Object._ [as *] (http://ethereum.github.io/browser-solidity/build/app.js:135296:17)
    at manageCallBack (http://ethereum.github.io/browser-solidity/build/app.js:69261:25)
    at AstWalker.walk (http://ethereum.github.io/browser-solidity/build/app.js:69236:7)
    at AstWalker.walk (http://ethereum.github.io/browser-solidity/build/app.js:69239:12)
    at AstWalker.walk (http://ethereum.github.io/browser-solidity/build/app.js:69239:12)
    at AstWalker.walk (http://ethereum.github.io/browser-solidity/build/app.js:69239:12)
    at AstWalker.walk (http://ethereum.github.io/browser-solidity/build/app.js:69239:12)
  | (anonymous) | @ | app.js:133722
-- | -- | -- | --
  | (anonymous) | @ | app.js:135298
  | _ | @ | app.js:135296
  | manageCallBack | @ | app.js:69261
  | AstWalker.walk | @ | app.js:69236
  | AstWalker.walk | @ | app.js:69239
  | AstWalker.walk | @ | app.js:69239
  | AstWalker.walk | @ | app.js:69239
  | AstWalker.walk | @ | app.js:69239
  | staticAnalysisRunner.runWithModuleList | @ | app.js:135295
  | staticAnalysisRunner.run | @ | app.js:135288
  | staticAnalysisView.run | @ | app.js:135389
  | (anonymous) | @ | app.js:135349
  | eventManager.trigger | @ | app.js:59481
  | compilationFinished | @ | app.js:130992
  | compileJSON | @ | app.js:130940
  | (anonymous) | @ | app.js:130899
  | gatherImports | @ | app.js:131117
  | internalCompile | @ | app.js:130894
  | compile | @ | app.js:130906
  | (anonymous) | @ | app.js:130584
  | Files.get | @ | app.js:132552
  | runCompiler | @ | app.js:130579
  | setTimeout (async) |   |  
  | editorOnChange | @ | app.js:130642
  | eventManager.trigger | @ | app.js:59481
  | (anonymous) | @ | app.js:131691
  | EventEmitter._signal | @ | app.js:18894
  | onChange | @ | app.js:23832
  | EventEmitter._signal | @ | app.js:18894
  | applyDelta | @ | app.js:22002
  | insertMergedLines | @ | app.js:21900
  | insert | @ | app.js:21828
  | insert | @ | app.js:24343
  | insert | @ | app.js:27511
  | $handlePaste | @ | app.js:27447
  | exec | @ | app.js:26499
  | (anonymous) | @ | app.js:25991
  | EventEmitter._emit.EventEmitter._dispatchEvent | @ | app.js:18884
  | exec | @ | app.js:26019
  | onPaste | @ | app.js:27438
  | onPaste | @ | app.js:17683
```

Please take a look - and fix it.

**Comment by PatchRanger** [comment]
Additional info: I can't deploy a contract using such configuration (remote Ethereum-node, which is connected via RPC with browser-solidity) - it alerts this message:

> Failed to publish metadata: hash mismatch

I have no idea what it means, may be it is a consequence of the console error, described above?

**Comment by yann300** [comment]
I will take a look at the issue you have.
for the error `Failed to publish metadata: hash mismatch` , that feature actually only deploy to swarm.
If you want to deploy an instance of the contract to the chain you are connected to, you should use `Create`.

**Comment by yann300** [comment]
could you drop here or pm me ( gitter.im/yann300 ) the contract you try to compile?

**Comment by PatchRanger** [comment]
@yann300 I am trying to deploy a contract from http://inaword.ru/bez-rubriki/kak-bystro-sozdat-smart-kontrakt-ico-na-ethereum/ (in Russian, please use Google Translate to get a translated version): I made changes as told in the article - and tried to deploy `MainSale` contract. When I switched from pushing Publish to pushing Create (as you suggested), the error changes to `insufficient funds for gas * price + value` - I guess, I am very close now, the only thing left is to deposit handful Ether to my account, thank you for the wise advice.

So the issue looks non-blocking.

**Comment by yann300** [comment]
try to increase the GasLimit in remix.  `3000000`  i could deploy `MainSale`

**Comment by yann300** [comment]
this particular error `Cannot read property 'relevantNodes' of undefined` is fixed. I think there is still another opened PR ( #707 )
