### ISSUE TITLE
Update colors/UI elements in Remix + remove style-guide from Browser-solidity

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/browser-solidity#706]

**Comment by ninabreznik** [comment]
@yann300 

Created 2 pull request needed to move style-guide to remix and export it to browser-solidity

https://github.com/ethereum/remix/pull/556
https://github.com/ethereum/browser-solidity/pull/717

**Comment by yann300** [comment]
can we close this @ninabreznik ?

**Comment by ninabreznik** [comment]
@ryestew Wherever that's possible in Remix file, we should replace existing colors with style-guide colors.

* only in JS files for now
* not in css (we first have to move things to JS files, so this comes in the next step)

HOW?

If there is a JS file with color, like for example
`color: ddd;`

it should be replaced with 
`color: ${styles.colors.grey}`

* if not sure which color, check colors from style guide and pick the closest
* in the file where you are using ${styles.colors.orange}, there should be
**style-guide required**

>In Remix repo
```js
var csjs = require('csjs-inject')
var styleGuide = require('./styles/style-guide')
var styles = styleGuide()
```

>In Browser-Solidity Repo
```js
var csjs = require('csjs-inject')
var styleGuide = remix.ui.styleGuide
var styles = styleGuide()
```
