### ISSUE TITLE
Delete Button Broken

### ISSUE THREAD

**Issue by Denton-L** [ethereum/browser-solidity#71]
# Expected Behaviour
After pressing the delete button, the file disappears and the next file is shown, or a blank screen if there are no other files.

# Current Behaviour
The file's tab is removed but the content still remains on screen. I am unable to edit anything or switch tabs. Opening up the Developer Console shows that every mouse movement, click or keystroke generates a JavaScript error.

# Reproduction
1. Create a new file.
2. Enter some text.
3. Press the X on the file to delete it.
4. Everything is now broken. Open the Developer Console for more information.

# Other Information
@redsquirrel, I did a `git bisect` and it appears that 0a37e6a3fbcd8be1e09affa6b860bb6d03143941 was the commit that broke it.

**Comment by redsquirrel** [comment]
Yes, same as #53. It's on my todo list.

**Comment by Denton-L** [comment]
Alright, thanks!
