### ISSUE TITLE
Event overloading isn't fully supported

### ISSUE THREAD

**Issue by yudilevi** [ethereum/browser-solidity#715]
Given contract:
```
pragma solidity ^0.4.11;

contract Test {
    event A(uint256 test1, uint256 test2);
    event A(uint256 test1, uint256 test2, uint256 test3);

    function Test() {
    }
    
    function test() {
        A(0, 0);
        A(1, 1, 1);
    }
}
```

Here's the event output when executing `test`:
```
A[
  "0",
  "0"
]

A"0x000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001"
```

Tested using solc 0.4.15.

The data seems to be correct but the formatting is broken.

**Comment by axic** [comment]
Seems that the ABI does not contain both events. @yudilevi has tried manually adding the event to the ABI with truffle and that solves it. Closing this assuming that is the problem and will be solved by a new Solidity release.
