### ISSUE TITLE
Publish to gist with remixd doesn't work 

### ISSUE THREAD

**Issue by 4000D** [ethereum/browser-solidity#735]
Contracts from remixd shared foleder cannot be published to gist.
Empty in browser directory, trying to publish `localhost/SomeContract.sol` to gist always outputs Unprocessable Entity error.

Doesn't support publishing contract to gist from remixd support yet?

![image](https://user-images.githubusercontent.com/8004585/29809437-1f2e82ce-8cd7-11e7-978d-a699869288bb.png)

**Comment by yann300** [comment]
no not yet sorry. only file from the browser storage are published. That 'll be updated soon.

**Comment by yann300** [comment]
opened another issue
