### ISSUE TITLE
Failed to publish metadata now happens on both https and http.

### ISSUE THREAD

**Issue by morfin** [ethereum/browser-solidity#758]
Since yesterday, I haven't been able to use remix anymore.

Anybody else facing the same problem?
<img width="887" alt="screen shot 2017-09-03 at 12 46 24 pm" src="https://user-images.githubusercontent.com/1243618/30002289-f6bfe42c-90a5-11e7-8716-dc26288b3667.png">

`XMLHttpRequest cannot load http://swarm-gateways.net/bzzr:/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://remix.ethereum.org' is therefore not allowed access. The response had HTTP status code 502.`

**Comment by casperdl** [comment]
I have exactly the same issue! Is there a solution to be expected soon?

thanks.

**Comment by MuhtasimTanmoy** [comment]
Same problem.

**Comment by yann300** [comment]
@MuhtasimTanmoy do you still have this issue?
I think that is fixed now. please reopen if not.

**Comment by smart-t** [comment]
This issue still appears to be there. When working with Ubuntu 16.04 LTS / latest solidity-browser ( commit 8540f374bc7c4c5136926e02818726e0c69f342c ) and Chrome.  My OSX seems to be fine with this. So solved depending on your perspective I think. Can someone please confirm, and re-open if it is not just me?

**Comment by stefek99** [comment]
I was searching how to solve the problem, found this github issue.

# https://


<img width="537" alt="screen shot 2017-11-05 at 11 07 54" src="https://user-images.githubusercontent.com/249703/32416591-afb7bbcc-c219-11e7-80ec-2b24696d1b8f.png">

<img width="760" alt="screen shot 2017-11-05 at 11 07 59" src="https://user-images.githubusercontent.com/249703/32416594-b447f904-c219-11e7-9661-3b5b0333e389.png">

# http://

<img width="536" alt="screen shot 2017-11-05 at 11 10 29" src="https://user-images.githubusercontent.com/249703/32416610-0b504986-c21a-11e7-945c-17b412fb9fa0.png">
