### ISSUE TITLE
Themeable REMIX

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/browser-solidity#770]
BRANCH: THEME (on remix and on browser-solidity)

TODOS:
* [x] **Replace ALL colors in existing JS files** in Remix and Browser solidity with the reference from style-guide.js ([see style guide](https://github.com/ethereum/remix/blob/master/src/ui/styles/style-guide.js))
* [x] **Remove styling from remaining css files** (universal-dapp.css and browser-solidity.css) into js files and use `csjs-inject` to add styling directly into JS files:
* [ ] **Add comments to injected css** (errors, .ace_gutter-cell.ace_breakpoint and display: block for rightpanel tabs): when we want to change styling for this, what does it affect (because it's not in the module, where we know what it refers to)
* [ ] **Apply theme to ace editor** (see solidity-mode.js)
* [ ] Fontawesome css and pygment_trac.css
* [ ] **Make a list of properties that we want to make modifiable** with different themes

**Comment by yann300** [comment]
One thing that will require a bit of work is to make ace editor themable also.
 ( https://github.com/ajaxorg/ace/tree/master/lib/ace/theme )
that might be sufficient to require another mode:
https://github.com/ethereum/browser-solidity/blob/master/src/app/editor/editor.js#L8

**Comment by yann300** [comment]
also this https://github.com/ethereum/browser-solidity/blob/master/src/app/editor/editor.js#L16
should be put in the theme
