### ISSUE TITLE
Include tests

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#8]
Adding tests somehow would be nice.

- [x] verify lint (will spot basic errors)
- [ ] unit tests
- [x] UI tests (using karma)
- [ ] integration tests for web3 (perhaps using testrpc)
- [x] build test (this is already covered I think)
- [ ] have separate travis entries for the tests

**Comment by axic** [comment]
- [ ] verify lint (will spot basic errors)
- [ ] unit tests
- [ ] UI tests (using karma)
- [ ] integration tests for web3 (perhaps using testrpc)
- [ ] build test (this is already covered I think)

**Comment by redsquirrel** [comment]
I'm researching UI tests. Karma is not going to work. It appears that nightwatch/Selenium are the way to go. I have an initial smoke test working on my laptop.

Assuming we want it to be automated via Travis, then I believe we're going to need to use SauceLabs. This requires the project to be registered. @chriseth or @axic, do you want to register browser-solidity at https://saucelabs.com/opensauce?

**Comment by chriseth** [comment]
Added open source: https://github.com/ethereum/browser-solidity/pull/89

**Comment by chriseth** [comment]
This is more or less working now, needs more tests.
