### ISSUE TITLE
File-explorer not overwriting exisiting file after confirm

### ISSUE THREAD

**Issue by ryestew** [ethereum/browser-solidity#803]
When you upload a file with the same name - the prompt asks you if you want to overwrite the file - when you click OK - the file does not change.  Nor does the alert happen that says the file didn't get uploaded.  I think the problem resides in these lines 
var fileReader = new FileReader()
      fileReader.onload = function (event) {
        var success = files.set(name, event.target.result)
        if (!success) modalDialogCustom.alert('Failed to create file ' + name)
        else events.trigger('focus', [name])
      }
      fileReader.readAsText(file)

**Comment by yann300** [comment]
should be fixed now
