### ISSUE TITLE
`address` input field gives `Error: Argument is not a number`

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/browser-solidity#809]
I tried a very simple smart contract:
```
contract c {
    address public a;
    function f(address _a) {
        a = _a;
    }
}
```
When calling `f` and entering e.g. `"0xca35b7d915458ef540ade6068dfe2f44e8fa733c"` I get an `Error: Argument is not a number` in the console. This used to work before and seems broken in the latest version of Remix.

**Comment by AdrianClv** [comment]
I'm having this same problem

**Comment by kuzyakiev** [comment]
Have the same issue
