### ISSUE TITLE
create and abstract contract

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#814]
Disallow to deploy / create if abstract contract (that was working before)

**Comment by ArturoLR** [comment]
This bug has been resolved?

**Comment by yann300** [comment]
you should not be able to create contract if it is abstract. the fix just pop up an alert if the contract is abstract

**Comment by ArturoLR** [comment]
I'm working with Ethereum Alarm Clock. The documentation (http://docs.ethereum-alarm-clock.com/en/latest/quickstart.html#scheduling-your-first-transaction) shows how create a schedule contract but requiere abstract contracts. There is another way to create abstract contracts or the issue will be fixed soon?

**Comment by yann300** [comment]
you can't create abstract contrac:  in their example nobody can't create `SchedulerInterface` . but you can create `DelayedPayment`
