### ISSUE TITLE
Disable auto compile by default

### ISSUE THREAD

**Issue by SmokinCaterpillar** [ethereum/browser-solidity#818]
Hi, whenever I load the remix website auto-compile is enabled even if I disabled it in previous sessions. In case I have larger contract opened, that sometimes takes 20 seconds to compile, remix is unusable on start-up. The same holds for refreshing the website.

Can you disable auto-compile by default? Hence, people have to opt-in to use it and not opt-out for disabling it? Thanks!

**Comment by yann300** [comment]
we've pushed a change: `autocompile` is still on by default. but you can disable it the status will be saved for the next reloads
