### ISSUE TITLE
File tab font, double clicks, upload tool tip

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/browser-solidity#83]
It seems like since the file upload icon was put in place, a couple of things have changed in the UI:
* The font in the file tabs has changed to something different (was this intentional?)
* If you double-click anywhere in the UI, the file upload dialog appears
* When you first focus your mouse anywhere in the UI, the "Upload" tool tip appears.

**Comment by Denton-L** [comment]
I think we can close this now.
