### ISSUE TITLE
Logs are removing trailing zeros from addresses

### ISSUE THREAD

**Issue by tomw1808** [ethereum/browser-solidity#844]
![grafik](https://user-images.githubusercontent.com/485781/31121341-14b4f5ea-a838-11e7-8fa0-cfadecfb41eb.png)

Had a simple contract, the logs in the panel removed the trailing zeros. See image.

I guess that is not really related to the contract you see in the pictures.

Contract for testing:

```
pragma solidity ^0.4.17;

contract SomeContract {
    event someEvent(address _someAddress);
    
    function someFunction() public {
        someEvent(0x010001Ac36dC609409458cC56C283F46B146a24d);
    }
}
```
Not sure if it's really a bug or not, but from my gut feeling it shouldn't be like that.

**Comment by yann300** [comment]
you're right , thanks for the report
