### ISSUE TITLE
Remix 0.4.17 weird behavior upon contract creation

### ISSUE THREAD

**Issue by barakman** [ethereum/browser-solidity#845]
After creating a contract, Remix seems to immediately execute each one of the public functions that I have in it.

Each one of them results with the following exception (shown in the terminal):

	undefined errored: VM error: invalid opcode.
		The constructor should be payable if you send value.
		The execution might have thrown.
		Debug the transaction to get more information. 

However, this message is not issued again when I execute these functions explicitly (i.e., from the `Run` pane).

In addition, it seems that the only transaction which has a `Details` button next to it (in the terminal) is the contract creation.

All other transactions have only a `Debug` button next to them, so I cannot observe attributes such as 'transaction cost', 'execution cost', etc.

For all it matters, I am using Firefox.

Thank you.

**Comment by yann300** [comment]
Remix execute all the constant functions after contract creation. that's normal.
but I think you should not have `VM error: invalid opcode.`  can you PM contract code?
Also `Call` does not yet have the Details Button. we'll add that soon

**Comment by barakman** [comment]
https://github.com/bancorprotocol/contracts/blob/improve_accuracy_and_performance/solidity/contracts/BancorFormula.sol

**Comment by yann300** [comment]
we changed the behavior so I think that's ok now. please reopen if not

**Comment by barakman** [comment]
Thank you.
Already been using Remix for at least a week without experiencing this problem.
