### ISSUE TITLE
Cannot find module './linker.js'

### ISSUE THREAD

**Issue by gaoqiaizhanglan** [ethereum/browser-solidity#847]
node v6.11.4
npm v3.10.10
npm install
Error: Cannot find module './linker.js' from '/home/gq/private-geth/browser-solidity/node_modules/solc'
[build       ]     at /home/gq/private-geth/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
[build       ]     at load (/home/gq/private-geth/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
[build       ]     at onex (/home/gq/private-geth/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
[build       ]     at /home/gq/private-geth/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
[build       ]     at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.10.0-35-generic
[build       ] npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "build"
[build       ] npm ERR! node v6.11.4
[build       ] npm ERR! npm  v3.10.10
[build       ] npm ERR! code ELIFECYCLE
[build       ] npm ERR! browser-solidity@0.0.0 build: `browserify src/index.js -o build/app.js`
[build       ] npm ERR! Exit status 1
[build       ] npm ERR! 
[build       ] npm ERR! Failed at the browser-solidity@0.0.0 build script 'browserify src/index.js -o build/app.js'.

**Comment by axic** [comment]
Fixed in latest solc-js.
