### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by slee981** [ethereum/browser-solidity#857]
My build failed with the following error message: 

########################################
mkdirp build; npm-run-all -ls downloadsolc build

[downloadsolc] 
[downloadsolc] > browser-solidity@0.0.0 downloadsolc /Users/stevelee/Documents/browser-solidity
[downloadsolc] > rimraf soljson.js; wget https://ethereum.github.io/solc-bin/soljson.js
[downloadsolc] 
[downloadsolc] sh: wget: command not found
[downloadsolc] npm ERR! file sh
[downloadsolc] npm ERR! code ELIFECYCLE
[downloadsolc] npm ERR! errno ENOENT
[downloadsolc] npm ERR! syscall spawn
[downloadsolc] npm ERR! browser-solidity@0.0.0 downloadsolc: `rimraf soljson.js; wget https://ethereum.github.io/solc-bin/soljson.js`
[downloadsolc] npm ERR! spawn ENOENT
[downloadsolc] npm ERR! 
[downloadsolc] npm ERR! Failed at the browser-solidity@0.0.0 downloadsolc script.
[downloadsolc] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[downloadsolc] 
[downloadsolc] npm ERR! A complete log of this run can be found in:
[downloadsolc] npm ERR!     /Users/stevelee/.npm/_logs/2017-10-05T20_57_37_278Z-debug.log
ERROR: "downloadsolc" exited with 1.
########################################

Any ideas how I can finish the install and use as a chrome extension? Is this a problem with the script or am I missing a dependency?

**Comment by hugo-dc** [comment]
The script downloadsolc is trying to use `wget` command to get `soljson.js`:

"downloadsolc": "rimraf soljson.js; wget https://ethereum.github.io/solc-bin/soljson.js",

You could try installing wget

**Comment by slee981** [comment]
Ah, of course! Worked great, thanks.
