### ISSUE TITLE
"Special characters are not allowed" when opening file

### ISSUE THREAD

**Issue by ethernomad** [ethereum/browser-solidity#872]
When I try to open a file from my localhost installation it says: "Special characters are not allowed"

**Comment by yann300** [comment]
what is the name of the file?

**Comment by ethernomad** [comment]
test.sol

Note this only happens on my localhost, not on https://remix.ethereum.org

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/browser-solidity/pull/877

**Comment by ethernomad** [comment]
Cool!
