### ISSUE TITLE
Static analyzer - require / assert

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#882]
if require/assert present: 

`use assert(x) if you never ever want x to be false, not in any circumstance (apart from a bug in your code). use require(x) if x can be false, due to e.g. invalid input or a failing external component.`

and link to the doc http://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions

**Comment by axic** [comment]
cc @soad003, you might be interested in this one

**Comment by soad003** [comment]
@yann300 should be a quick one. Try to make it next week.

**Comment by vm06007** [comment]
so how to avoid this warning @soad003 ??

**Comment by yann300** [comment]
afak that is not "avoidable", when you use assert or require the analyzer just make sure the developer knows what are the implication of using it

**Comment by vm06007** [comment]
okay thanks!
