### ISSUE TITLE
Fails to compile when passing function as parameters

### ISSUE THREAD

**Issue by ismaelbej** [ethereum/browser-solidity#889]
This contracts compile correctly with offline compiler and executes properly

But 'Start to compile' button keep spinning and never finishes (in both "Auto compile" and manual compilation). Also tried compiler v0.4.15 with the same results (have to replace pure by constant).

```
pragma solidity ^0.4.18;

contract B {
    function plus(uint a, uint b) pure internal returns (uint) {
        return a + b;
    }

    function eval(function (uint, uint) pure internal returns (uint) f, uint x, uint y) pure internal returns (uint) {
        return f(x, y);
    }

    function calc(uint x, uint y) pure public returns (uint) {
        return eval(plus, x, y);
        // return plus(x, y);
    }
}
```

In chrome developer console this stack trace appears

```
(6)app.js:147559 static analysis functionCallGraph.js: B.f(uint256,uint256) not found in function call graph.
(2)app.js:148095 Uncaught TypeError: Cannot read property '1' of null
    at getFunctionCallTypeParameterType (app.js:148095)
    at isBuiltinFunctionCall (app.js:148212)
    at Object.isLocalCallGraphRelevantNode (app.js:148203)
    at app.js:147249
    at checksEffectsInteraction.visit (app.js:147054)
    at app.js:148698
    at Array.map (<anonymous>)
    at Object._ [as *] (app.js:148696)
    at manageCallBack (app.js:84256)
    at AstWalker.walk (app.js:84231)
```

When commenting 'eval' call and using 'plus' function directly it compiles without problem and executes correctly.

Hope this helps! Cheers!

**Comment by yann300** [comment]
@soad003 could you take a look at this? I think you'll have more clue than us about how to fix that

**Comment by soad003** [comment]
@yann300 i will take a look. I probably have to add proper handling for function parameters. I general i think we should catch errors in the static analysis modules and add an error message in the analysis tab instead of just leting the whole compilation fail!

**Comment by yann300** [comment]
true!

**Comment by yann300** [comment]
adding some `catch`
