### ISSUE TITLE
Outdated Syntax Highlighting

### ISSUE THREAD

**Issue by Denton-L** [ethereum/browser-solidity#90]
The syntax highlighter is pretty outdated. It has not been updated since May 6th, at latest. It is missing many keywords and special constants.

The keywords should be able to be found here: https://github.com/ethereum/solidity/blob/develop/libsolidity/parsing/Token.h

**Comment by axic** [comment]
I think this is related to #69.

**Comment by Denton-L** [comment]
Sorry, I didn't check the issues thoroughly enough.
