### ISSUE TITLE
Compiler details - Copy to clipboard [object Object]

### ISSUE THREAD

**Issue by DeltaBalances** [ethereum/browser-solidity#905]
Found this on the compile tab, clicking on details to see the abi and bytecode.
Every section has a 'copy value to clipboard' button, which works fine for metadata, abi, webdeploy, etc.

However  FUNCTIONHASHES and GASESTIMATES  return '[object Object]' to my clipboard.
Shouldn't this be the raw version like it is displayed? (JSON.stringify)

**Comment by yann300** [comment]
fixed by https://github.com/ethereum/browser-solidity/pull/886
