### ISSUE TITLE
Ask To Confirm Transaction

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#938]
- [ ] If Main net, prompt the user with transaction infos like:
 - from
 - to
 - transaction value 
 - gasLimit
 - gasPrice
 - Data
and ask him to confirm

- [ ] in settings tab, add this checkbox (default unselected) (value is pesisted in storage) : 
 "ask to confirm transaction" (remix will always ask if network is Mainnet"

**Comment by ninabreznik** [comment]
@yann300 If I understand correctly - if you select a main network on Metamask for example, and then click create contract instance, then the modal dialog should appear? What if user clicks At Address?

**Comment by yann300** [comment]
This modal should appear only when a tx is about to be sent. In the code, that should be just before the `sendTransaction`.

**Comment by yann300** [comment]
When click `at address`. we just popup a new instance but without creating any tx.
btw I forgot that: we should also display gas estimation

**Comment by golyalpha** [comment]
Wait, shouldn't the wallet itself (like MetaMask) handle the showing of a modal dialog?

**Comment by yann300** [comment]
In case of metamask yes but if you use another `Web3 provider`, not

**Comment by ninabreznik** [comment]
So when Metamask is selected, we don't show the popup?

**Comment by yann300** [comment]
I think we can just show it up everytime for now (cause it will show the gas estimation too). If the flow is too slow we could think of optionnally disable the feature when metamask is used , but not now

**Comment by ninabreznik** [comment]
👍
