### ISSUE TITLE
retrieveMetadataHash broken for experimental flags

### ISSUE THREAD

**Issue by cdetrio** [ethereum/browser-solidity#950]
If a contract uses `pragma experimental ABIEncoderV2;` then the metadata bytes at the end of the compiled bytecode will look something like:  `a265627a7a723058203fa309d6a5ebe26d47114c7b507bad571e92de35a58995d682592c03f8340db06c6578706572696d656e74616cf50037`.

These bytes are [CBOR encoded](http://cbor.me/) for metadata `{"bzzr0": h'3FA309D6A5EBE26D47114C7B507BAD571E92DE35A58995D682592C03F8340DB0', "experimental": true}`

Without the experimental flag, the metadata bytes are `a165627a7a723058200cb6da6ad151413a6e8b63f2287dca07252633ffb06b25b63c8e3297d680c7ec0029` which decode to `{"bzzr0": h'0CB6DA6AD151413A6E8B63F2287DCA07252633FFB06B25B63C8E3297D680C7EC'}`.

The function `retrieveMetadataHash` parses the metadata using a regex that only works for metadata without the experimental flag:

https://github.com/ethereum/browser-solidity/blob/a8fc820723db6b7ce4e20c709dd13578d92838e1/src/app/contract/contractParser.js#L48-L53

**Comment by yann300** [comment]
fix https://github.com/ethereum/browser-solidity/pull/974
