### ISSUE TITLE
lastOp is undefined on contract created by another contract

### ISSUE THREAD

**Issue by golyalpha** [ethereum/browser-solidity#955]
Basically, I have two contract definitions, I create one, that's supposed to create the other one once I run a method, and add it's address to a public array once it's created and set up, which it does. But when I try to interact with the other contract, by adding it's address to the list of contracts in Remix, every time I try to do something, I get lastOp is undefined.

For more details, and contract source code:
[Question from ETH Stack Exchange](https://ethereum.stackexchange.com/questions/33219/lastop-is-undefined)

**Comment by yann300** [comment]
do you still have the issue now on remix.ethereum.org ?

**Comment by golyalpha** [comment]
Yes, unfortunately.

**Comment by golyalpha** [comment]
Here's the console output:
```
creation of NaniteFactory pending...
[vm] from:0xca3...a733c, to:NaniteFactory.(constructor), value:0 wei, data:0x606...10029, 0 logs, hash:0x7bf...76ca1
transact to NaniteFactory.accessNonce pending ... 
[vm] from:0xca3...a733c, to:NaniteFactory.accessNonce() 0x692...77b3a, value:0 wei, data:0x612...21422, 0 logs, hash:0x0c3...f3854
transact to NaniteFactory.createNanite pending ... 
[vm] from:0xca3...a733c, to:NaniteFactory.createNanite() 0x692...77b3a, value:0 wei, data:0x33b...3d6bb, 0 logs, hash:0x83a...61f72
call to NaniteFactory.nanites
[call] from:0xca35b7d915458ef540ade6068dfe2f44e8fa733c, to:NaniteFactory.nanites(uint256), data:8536e...00000, return: 
{
	"0": "address: 0x755014da263fc47d238078bb47d217f743e5b6a5"
}
call to Nanite.Price
call to Nanite.Price errored: lastOp is undefined 
call to Nanite.dna
call to Nanite.dna errored: lastOp is undefined 
```

**Comment by yann300** [comment]
well could you PM the code please?

**Comment by golyalpha** [comment]
It's in the Ethereum Stack Exchange post, linked in the opener of this issue, but sure.

**Comment by yann300** [comment]
For now, you could try
 -  removing the line `Nanite(newNanite).sell(10 finney);` 
check https://github.com/ethereumjs/ethereumjs-vm/pull/236 for the fix
or 
 - using geth or any external node

Anyway this `lastOp is undefined` should not pop up like this and requires a check in Remix.

**Comment by golyalpha** [comment]
The problem is, that the debugger says it's passed. (It even pushes the contract's address to the list of addresses.) Anyways, yeah, gonna try that now.

**Comment by golyalpha** [comment]
Ok, yeah, now I am not getting that particullar issue, but it definitely needs a fix in the IDE.

By the way, any idea why does the DNA array look like this:
```
call to Nanite.dna
[call] from:0xca35b7d915458ef540ade6068dfe2f44e8fa733c, to:Nanite.dna(uint256), data:f666e...00000, return: 
{
	"0": "bytes32: 0x147f948a2387a200a429d84830937276bbf4a5e056b44466e8f88d2563635adc"
}
```
After being constructed like this:
```
uint nonce = uint(NaniteFactory(owner).accessNonce());
for (uint i=0;i<256/32;i++){
    dna.push(keccak256(now + i + nonce));
}
```

**Comment by yann300** [comment]
you are not accessing the array but you are accessing one item of it

**Comment by golyalpha** [comment]
Oh, so, how do I access the whole array?

**Comment by yann300** [comment]
I think this is fixed now, please reopen if not.
to return the entire array, I think creating a getter should do the trick
