### ISSUE TITLE
Code Optimization is not working

### ISSUE THREAD

**Issue by pabloruiz55** [ethereum/browser-solidity#956]
Remix's code optimization seems not to be working.
Even when the option is turned on from settings, the gas consumption is not modified. 
Also, when exploring the contract details it says: `optimizer - enabled:false`

<img width="371" alt="screen shot 2017-12-15 at 1 54 19 pm" src="https://user-images.githubusercontent.com/526558/34052131-cf52ab9a-e19f-11e7-8471-bcddae78e9c1.png">

<img width="254" alt="screen shot 2017-12-15 at 1 53 53 pm" src="https://user-images.githubusercontent.com/526558/34052134-d16b1930-e19f-11e7-895f-bb9b561c5281.png">

**Comment by yann300** [comment]
fixed
