### ISSUE TITLE
string mapping causes solidity state to not load

### ISSUE THREAD

**Issue by inject-it** [ethereum/browser-solidity#965]
When a string mapping like mapping(string => uint) _iBreakSolidityState; is provided in code, it breaks the ability to debug the solidity state.

Take a simple solidity contract.
```
pragma solidity ^0.4.19;

contract SimpleState {
    uint _num;
    mapping(string => uint) _iBreakSolidityState; // redundant but breaks debugging
    function updateNum(uint num) public {
        _num = num;
    }
}
```

**Steps to reproduce:**
1. In Javascript VM mode, deploy the contract
2. Call updateNum with any valid number.
3. Debug function call
4. Step through to end
5. View **Solidity State** is not working, forever loading

Now modify the above removing mapping(string => uint) _iBreakSolidityState; and you'll see it works as expected.

Most likely related, there is also a JS error in the developer console log complaining about trim() not being found.

**Comment by yann300** [comment]
fixed https://github.com/ethereum/remix/pull/648
