### ISSUE TITLE
old solc versions don't work

### ISSUE THREAD

**Issue by cdetrio** [ethereum/browser-solidity#967]
The old solc versions don't work when selected in the Settings tab. Only working versions should appear in the drop-down.

**Comment by ewiner** [comment]
I'm seeing the same thing.  Specifically, on 0.4.10 and below, I'm seeing this error when I try to construct my contract:

> TypeError: Cannot convert undefined or null to object

It works fine on any newer version of solc.  And I'm not sure how to get more detailed information or a stack trace on that error - there's nothing in the JS console.
