### ISSUE TITLE
Suspected bug in compiler or in optimizer

### ISSUE THREAD

**Issue by barakman** [ethereum/browser-solidity#972]
I have a purely stateless contract with 3 functions - `log`, `floorLog` and `exp`.
I am testing the gas-estimate of function `log`, which calls function `floorLog`.
Function `exp` is just a dummy function which returns a constant value.

The estimated gas of function `log` changes dramatically, depending on this constant value.

For example, running `log(123456, 25000)` on Remix IDE, I get:
- When set to 0x080000000000000000000000000000000:
  - transaction cost = 51119 gas
  - execution cost = 29271 gas
- When set to any value other than 0x080000000000000000000000000000000:
  - transaction cost = 42866 gas
  - execution cost = 21018 gas

Note that 0x080000000000000000000000000000000 is (also) the value of the global constant `FIXED_1`.
This constant is used in function log, and I'm suspecting that the optimizer somehow messes things up because of this.

I initially ran into the problem while testing via Web3 + TestRPC, so I posted it also at https://github.com/ethereum/solc-js/issues/171.

The contract is provided hereby:

```
pragma solidity ^0.4.18;

contract PriceCalculator {
    uint256 private constant ONE = 1;
    uint8 private constant PRECISION = 127;
    uint256 private constant FIXED_1 = 0x080000000000000000000000000000000;
    uint256 private constant FIXED_2 = 0x100000000000000000000000000000000;
    uint256 private constant MAX_NUM = 0x1ffffffffffffffffffffffffffffffff;

    function log(uint256 numerator, uint256 denominator) public pure returns (uint256) {
        uint256 res = 0;

        assert(numerator <= MAX_NUM);
        uint256 x = numerator * FIXED_1 / denominator;

        // If x >= 2, then we compute the integer part of log2(x), which is larger than 0.
        if (x >= FIXED_2) {
            uint8 count = floorLog(x / FIXED_1);
            x >>= count; // now x < 2
            res = count * FIXED_1;
        }

        // If x > 1, then we compute the fraction part of log2(x), which is larger than 0.
        if (x > FIXED_1) {
            for (uint8 i = PRECISION; i > 0; --i) {
                x = (x * x) / FIXED_1; // now 1 < x < 4
                if (x >= FIXED_2) {
                    x >>= 1; // now 1 < x < 2
                    res += ONE << (i - 1);
                }
            }
        }

        return res;
    }

    function floorLog(uint256 n) public pure returns (uint8) {
        uint8 res = 0;

        if (n < 256) {
            // At most 8 iterations
            while (n > 1) {
                n >>= 1;
                res += 1;
            }
        }
        else {
            // Exactly 8 iterations
            for (uint8 s = 128; s > 0; s >>= 1) {
                if (n >= (ONE << s)) {
                    n >>= s;
                    res |= s;
                }
            }
        }

        return res;
    }

    function exp(uint256 x) public pure returns (uint256) {
        return 0x080000000000000000000000000000000;
    }
}
```

UPDATE:

This appears to be a problem in the optimizer:

For example, running `log(123456, 25000)`, I get:
- When set to 0x080000000000000000000000000000000:
  - transaction cost = 52385 gas without optimizer, 51119 gas with optimizer
  - execution cost = 30537 gas without optimizer, 29271 gas with optimizer
- When set to any value other than 0x080000000000000000000000000000000:
  - transaction cost = 52385 gas without optimizer, 42866 gas with optimizer
  - execution cost = 30537 gas without optimizer, 21018 gas with optimizer

So it seems that Remix is unable to optimize the code with this value is (re)used.

**Comment by axic** [comment]
Issue opened on wrong repo.
