### ISSUE TITLE
Remix Interface on Right Hand Side is Missing Contract Category

### ISSUE THREAD

**Issue by ericsarabia** [ethereum/browser-solidity#977]
Why does my Remix interface look different from the Remix interfaces I've been seeing on tutorials? Specifically, others have the following tabs on their right hand panel: Contract/Settings/Files/Debugger/Analysis/Docs 

whereas I have Compile/Run/Settings/Debugger/Analysis/Support

This is important because it's in the Contract section that you can see the "Publish" "At Address" and "Create" buttons.

See the attached screenshots.
![screenshot 2018-01-03 09 24 59](https://user-images.githubusercontent.com/8852194/34532592-85ba9eae-f06b-11e7-92cb-f48b4d5ef332.png)
![screenshot 2018-01-03 09 21 58](https://user-images.githubusercontent.com/8852194/34532593-85dd72d0-f06b-11e7-94ca-61c2111f93a4.png)

**Comment by chainhead** [comment]
But, wouldn' the option to Create and Load from address (as highlighted in first screenshot) acheive the same?

**Comment by yann300** [comment]
because the interface changed. but the same functionalities are present
