### ISSUE TITLE
Cursor gets farther away as I type

### ISSUE THREAD

**Issue by flavius717** [ethereum/browser-solidity#980]
![remixbug1](https://user-images.githubusercontent.com/34523373/34613529-1f87b24c-f1fc-11e7-9153-df1b9c29c9b6.png)

![remixbug2](https://user-images.githubusercontent.com/34523373/34613538-2538228a-f1fc-11e7-83a0-c35912278200.png)

![remixbug](https://user-images.githubusercontent.com/34523373/34613391-9d25b038-f1fb-11e7-93cf-eac455fab41d.png)

Running in Chromium on Arch Linux.

**Comment by yann300** [comment]
which version of Chromium?

**Comment by flavius717** [comment]
Apologies for not getting back to you sooner.

> Version 63.0.3239.132 (Developer Build) (64-bit)

**Comment by wowa1983** [comment]
? Wie bitte

Am 15.01.2018 23:50 schrieb "flavius717" <notifications@github.com>:
