### ISSUE TITLE
error "mock compiler: source not found"

### ISSUE THREAD

**Issue by nicos99** [ethereum/browser-solidity#982]
I'm using Remix on a new system (Win10 64 bits) but I can't compile any solidity code (for instance the ballot sample) on FireFox 57.0.3 (64 bits) (alias Quantum), I get an error message : "mock compiler: source not found". There is no error trace in the FireFox console.
I do not have this problem with Chrome (version 63.0.3239.132 (Build officiel) (64 bits)) nor Edge (41.16299.15.0)

**Comment by yann300** [comment]
In the settings tab, try to change the compiler version (to the last one).
the `soljson.js` used for testing has been commited by mistake (I removed it).

**Comment by centraleprice** [comment]
the compile always gives to me an error message that ( Unable to import "browser/CPRERC20.sol": File not found ) and CPR it's my token ether 
please help

**Comment by sunman66** [comment]
the same mistake, i can't change settings
